"""E1: self-similar extension that keeps every process itself picks coasting expansion.

Test family (an example, not a premise): spatially flat FRW, ds^2 = -dt^2 + t^(2p) dx^2.
It has a homothety t -> lam t, x -> lam^(1-p) x (ds^2 -> lam^2 ds^2), generated by xi = t d_t + (1-p) x d_x.
Requirements: A5 (extension has no preferred scale -> the law is invariant under a homothety) and M4
(extension does not change which process is which -> the homothety maps each comoving worldline x = const
to itself). xi is tangent to every x = const iff p = 1: coasting, a = t.
Also computes, for comparison with the observed universe, H t along a flat LCDM history.
Output: calc/out/e1_selfsimilar_extension.txt
"""
import math
import os
import sympy as sp

OUT = os.path.join(os.path.dirname(__file__), "out", "e1_selfsimilar_extension.txt")
lines = []


def say(s=""):
    print(s)
    lines.append(s)


t, x, lam, p = sp.symbols("t x lam p", positive=True)
# homothety check: pull back ds^2 under t -> lam t, x -> lam^(1-p) x
dt, dx = sp.symbols("dt dx")
ds2 = -dt**2 + t**(2 * p) * dx**2
ds2_h = (-(lam * dt)**2 + (lam * t)**(2 * p) * (lam**(1 - p) * dx)**2)
say(f"homothety: ds^2 after / before = {sp.simplify(ds2_h / ds2)}   (should be lam^2)")
xi_x = (1 - p) * x
say(f"x-component of the homothety generator: {xi_x}; vanishes for every x iff p = 1")

# comparison: H t in flat LCDM (Omega_m = 0.315, Omega_L = 0.685), radiation neglected
Om, OL = 0.315, 0.685
def H(a):  # in units of H0
    return math.sqrt(Om / a**3 + OL)
def t_of_a(a, n=200000):  # H0 t = integral_0^a da / (a H)
    s, prev = 0.0, 0.0
    for i in range(1, n + 1):
        ai = a * i / n
        f = 1.0 / (ai * H(ai))
        s += 0.5 * (f + prev) * (a / n) if i > 1 else f * (a / n) * 0.5
        prev = f
    return s
say("\nflat LCDM (Omega_m = 0.315): H t along the history (coasting would give H t = 1 always)")
for a in (0.1, 0.3, 0.5, 0.7, 0.9, 1.0, 1.2, 1.5, 2.0):
    say(f"  a = {a:4.1f}:  H t = {H(a) * t_of_a(a):.4f}")
# where does H t cross 1
lo, hi = 0.5, 2.0
for _ in range(50):
    mid = 0.5 * (lo + hi)
    if H(mid) * t_of_a(mid, 20000) < 1:
        lo = mid
    else:
        hi = mid
say(f"  H t = 1 at a = {0.5 * (lo + hi):.3f} (today a = 1); observed H0 t0 = 67.4 km/s/Mpc x 13.8 Gyr = {67.4 / 977.8 * 13.797:.3f}")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")
