/-
# The coupling was there all along: two scalings make a rotation

`Expressive.lean` diagnosed the framework's weakness as the scale channel and
the rotation channel being independent *by construction*, and concluded that
progress needs a coupling between them which the axioms do not supply.

That diagnosis was reached by analysing `Foundation.scale`, which takes the
scale to be the abelianization on the argument that "scales are ratios, and
ratios commute".  **That argument is about a scalar scale.**  A4 does not
provide a scalar scale; it provides one scale *per direction*.  And scalings
along different directions do not commute.

This is the third appearance of the same substitution — scalar reasoning where
the axiom is directional — after `Frame.lean` (geometry) and `Axis.lean`
(defects).  Here it was at the foundation, and correcting it supplies exactly
the coupling that was said to be missing.

**The coupling is forced by what the words mean.**  A scaling is a pure stretch:
it changes lengths along its axes and rotates nothing, so as an operator it is
*symmetric*.  A rotation changes no length, so it is *antisymmetric*.  Then:

* `bracket_scaling_scaling` — the bracket of two scalings is **antisymmetric**:
  two scalings in different directions compose, in the two orders, to results
  differing by a **rotation**.  Nothing is chosen; symmetry of the generators
  forces it;
* `bracket_rotation_scaling` — a rotation and a scaling bracket to a scaling,
  so rotations move the scaling axes around;
* `bracket_rotation_rotation` — rotations close among themselves.

Together these are the whole structure: `[S,S] ⊆ A`, `[A,S] ⊆ S`, `[A,A] ⊆ A`.
The scale sector is **not** a subalgebra, and its failure to be one lands
exactly in the rotation sector.

`boost_bracket_eq_rotation` makes it concrete: two directional scalings on a
three-dimensional space bracket to a definite rotation, computed entry by
entry.

**What this changes.**

1. `Foundation.scale` as an abelianization describes the *scalar* case only.
   With a directional scale the scalings do not form an abelian quotient — they
   generate the rotations.
2. `Expressive.channels_independent` is therefore a statement about the scalar
   sector, not about the framework.  **The channels are coupled**, and maximally
   so: the rotation sector is *generated* by the scale sector.
3. This is consistent with everything already proved.
   `Connection.curv_pure_scale_eq_zero` says a pure-scale connection is flat —
   and a *single* scaling direction is exactly the case where no bracket is
   available, so no rotation is generated and there is no curvature.
   `Frame.isotropic_reciprocal_forces_flat` is the same fact from the metric
   side.  **One direction: flat.  Two or more: curvature, generated by the
   scalings themselves.**

Physically this is the Thomas–Wigner rotation: two boosts in different
directions compose to a boost *and a rotation*.  Terrell–Penrose is its visual
form — a rapidly moving object is seen rotated rather than contracted, because
the scale change is being read as a rotation.  Neither is imported here; both
are what the bracket of two symmetric generators is.
-/
import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.NoncommRing
import Mathlib.Tactic.FinCases
import SCD.Quantum

namespace SCD.Coupling

open Matrix SCD.Quantum

variable {n : Type*} [Fintype n] [DecidableEq n]

/-! ## What the two words mean, as operators -/

/-- A **scaling**: a pure stretch.  It changes lengths and rotates nothing, so
as an operator it is symmetric. -/
def IsScaling (S : Matrix n n ℝ) : Prop := Sᵀ = S

/-- A **rotation generator**: it changes no length, so it is antisymmetric. -/
def IsRotation (A : Matrix n n ℝ) : Prop := Aᵀ = -A

/-- The bracket of two operators.

This is `Quantum.ad` and not a second construction: `ad p a = p a − a p` in any
ring, and matrices are a ring.  It was declared separately here, and
`Dynamics.nonflat_witness` had to observe that the two agree by `rfl` — which is
the signature of one notion carrying two names.  The abbreviation keeps the
bracket notation where the Lie-theoretic reading wants it while making the
identification definitional.

The identification is not cosmetic.  `Connection.lean` builds curvature as
`ad` of two transports and `Quantum.lean` builds `ħ` as `ad` of two phase-space
translations; this file builds rotation as `ad` of two scalings.  **All three are
the same construction on three families of operators**, which is a stronger
statement than the analogy the files previously drew. -/
abbrev br (S T : Matrix n n ℝ) : Matrix n n ℝ := ad S T

/-- Recorded explicitly: the bracket of the scaling sector and the commutator
that produces `ħ` are one operation. -/
theorem br_eq_ad (S T : Matrix n n ℝ) : br S T = ad S T := rfl

/-! ## The coupling -/

/-- **Two scalings bracket to a rotation.**

This is the coupling `Expressive.lean` said was missing, and it is not put in by
hand: if both generators are symmetric then their commutator is antisymmetric,
by transposition alone.

So a scale change along one direction followed by one along another differs
from the reverse order **by a rotation**.  With a scalar scale there is only one
direction and the bracket is unavailable; with a directional scale it is
unavoidable. -/
theorem bracket_scaling_scaling {S T : Matrix n n ℝ}
    (hS : IsScaling S) (hT : IsScaling T) : IsRotation (br S T) := by
  simp only [IsScaling] at hS hT
  simp only [IsRotation, br, ad, transpose_sub, transpose_mul, hS, hT]
  noncomm_ring

/-- **A rotation and a scaling bracket to a scaling**: rotations move the
scaling axes without creating new rotations. -/
theorem bracket_rotation_scaling {A S : Matrix n n ℝ}
    (hA : IsRotation A) (hS : IsScaling S) : IsScaling (br A S) := by
  simp only [IsRotation] at hA
  simp only [IsScaling] at hS
  simp only [IsScaling, br, ad, transpose_sub, transpose_mul, hA, hS]
  noncomm_ring

/-- **Rotations close among themselves.** -/
theorem bracket_rotation_rotation {A B : Matrix n n ℝ}
    (hA : IsRotation A) (hB : IsRotation B) : IsRotation (br A B) := by
  simp only [IsRotation] at hA hB
  simp only [IsRotation, br, ad, transpose_sub, transpose_mul, hA, hB]
  noncomm_ring

/-- Collected: the scale sector is **not** a subalgebra, and its failure to be
one lands exactly in the rotation sector.  `[S,S] ⊆ A`, `[A,S] ⊆ S`,
`[A,A] ⊆ A`. -/
theorem coupling_structure {S T A B : Matrix n n ℝ}
    (hS : IsScaling S) (hT : IsScaling T) (hA : IsRotation A) (hB : IsRotation B) :
    IsRotation (br S T) ∧ IsScaling (br A S) ∧ IsRotation (br A B) :=
  ⟨bracket_scaling_scaling hS hT, bracket_rotation_scaling hA hS,
   bracket_rotation_rotation hA hB⟩

/-! ## One direction generates nothing -/

/-- **A single scaling direction produces no rotation.**  Its bracket with
itself vanishes, so nothing is generated — which is why a scalar scale gives a
flat geometry (`Connection.curv_pure_scale_eq_zero`,
`Frame.isotropic_reciprocal_forces_flat`).  Curvature needs at least two scale
directions. -/
@[simp] theorem bracket_self (S : Matrix n n ℝ) : br S S = 0 := by
  simp only [br, ad, sub_self]

/-- More generally, commuting scalings generate no rotation: the coupling
switches on exactly when the scale is genuinely directional. -/
theorem no_rotation_of_commuting {S T : Matrix n n ℝ} (h : S * T = T * S) :
    br S T = 0 := by
  simp only [br, ad, h, sub_self]

/-! ## Concretely, in three dimensions

Two directional scalings in the `0`–`1` and `0`–`2` planes.  Their bracket is
computed entry by entry and is a definite rotation in the `1`–`2` plane. -/

/-- Scaling in the `0`–`1` plane. -/
def K₁ : Matrix (Fin 3) (Fin 3) ℝ := !![0, 1, 0; 1, 0, 0; 0, 0, 0]

/-- Scaling in the `0`–`2` plane. -/
def K₂ : Matrix (Fin 3) (Fin 3) ℝ := !![0, 0, 1; 0, 0, 0; 1, 0, 0]

/-- Rotation in the `1`–`2` plane. -/
def J : Matrix (Fin 3) (Fin 3) ℝ := !![0, 0, 0; 0, 0, 1; 0, -1, 0]




/-- **The bracket of the two scalings is exactly the rotation.**

`[K₁, K₂] = J`.  Two pure stretches, in different directions, compose in the two
orders to results differing by a rotation — computed here entry by entry with
no appeal to any group theory. -/
theorem boost_bracket_eq_rotation : br K₁ K₂ = J := by
  simp only [br, ad, K₁, K₂, J]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_three]

/-- In particular the two scalings do **not** commute, so the scale sector is
not abelian once it is directional. -/
theorem scalings_do_not_commute : K₁ * K₂ ≠ K₂ * K₁ := by
  intro h
  have hbr : br K₁ K₂ = 0 := no_rotation_of_commuting h
  rw [boost_bracket_eq_rotation] at hbr
  have h12 : (J : Matrix (Fin 3) (Fin 3) ℝ) 1 2 = 0 := by rw [hbr]; rfl
  simp [J] at h12

end SCD.Coupling
