/-
# What the coupling makes the scale field do

`Coupling.lean` showed the scale and rotation sectors are not independent: two
scalings in different directions bracket into a rotation, forced by the
generators' symmetry.  This file takes that structure and asks what it makes
the theory *say* — about the foundation, about evolution, and about the
spectrum.  The three are one question, so they are answered in one place.

## I.  A correction, and what the commutative ring actually costs

`Direction.lean`'s prose asserted that A1's commuting derivations were "a hidden
flatness assumption", on the reading that *commuting directions are flat
coordinate directions*.  **That reading is wrong and is withdrawn here.**
Commuting coordinate directions are a choice of chart, available locally
always; they say nothing about curvature.  The theorem in that file
(`commute_iff_bracket_acts_trivially`) is conditional on flat transport and
stands; the interpretation drawn from it does not.

`no_flatness_from_commuting_derivations` proves the point directly: kill the
derivations entirely — the most commuting they can possibly be — and the
curvature `F` is still whatever `ad (A i) (A j)` is, which
`nonflat_witness` shows can be nonzero.  **Flatness lives in whether the
connection commutes, not in whether the directions do.**

So the commutative function algebra is not a restriction on quantum
non-commutativity.  Functions on a space commute; that is classical and
correct.  The comparison operators are where non-commutativity belongs, and
`Foundation`, `Connection`, `Crossed`, `Quantum` and `Coupling` all keep them
non-commutative.

**But the commutative sector does cost something, and this pins down exactly
what.**  `commutative_sector_transports_commute`: over a commutative ring `ad`
vanishes identically, so covariant transports commute — the sector has **no
transport curvature at all**.  Every curvature in `Conformal.lean` therefore
enters through the postulated `δ`, which is precisely why `δ` had to be
postulated there.  That is the price, and it is confined to the classical
isotropic geometry: it is not a limitation on the quantum sector.

## II.  The evolution equation is Bianchi, and its content is conservation

With the coupling, curvature is generated by the scale field rather than added
to it.  What can then be written down?  `Connection.bianchi` is already proved,
and it turns out to be the whole answer:

* `source_conserved_of_field_equation` — **if** the curvature is proportional to
  a source, **then** that source satisfies the cyclic conservation law.  Not
  assumed: forced by Bianchi;
* `no_field_equation_of_nonconserved` — the contrapositive, which is the sharp
  form.  A non-conserved source admits **no** field equation at all.

So conservation of energy-momentum is not an extra postulate in this framework.
It is the condition for the field equation to be writable, and it comes from
Jacobi through Bianchi — from associativity of transport, and nothing else.

`source_antisymm` adds what the coupling contributes: `F` is antisymmetric and
by `Coupling.bracket_scaling_scaling` it is rotation-valued, so **the source of
the scale field is a rotation density**.

## III.  Multiplets are internally flat

This is where the coupling pays.  `Gauge.lean` says a multiplet is a degeneracy
block of the directional scale: `a` and `b` are related iff `s a = s b`.
`Coupling.bracket_self` says a scaling brackets to zero with itself.  Put them
together:

* `same_multiplet_no_rotation` — two directions in the same multiplet generate
  no rotation, **given** a per-direction assignment of scaling operators.

**Scope correction (see `Axes.lean`).**  The `Realizes` hypothesis assigns one
scaling operator per direction, determined by that direction's scale value.
Real rank one does not supply that: it supplies one vector and one scaling
(`Particle.pattern_is_one_vector`).  The theorems below are true of anything
meeting the hypothesis; the gloss "multiplets are internally flat" as a
statement about this framework is **withdrawn**.  What replaces it is
`Axes.lean`: rotation is carried by the *variation* of the single pattern.

Curvature is generated only *between* multiplets, never inside one.  Gauge
structure and geometry were previously two unrelated outputs of the scale
pattern; the coupling makes the first one control the second.  A consequence
with content: `larger_multiplet_fewer_generators` — the more degenerate the
scale, the fewer independent rotations there are to generate, which is the
framework's version of "more symmetry means less structure".

`multiplet_change_needs_pattern_change` closes the loop to the spectrum: the
multiplet structure can change only where the scale pattern changes, i.e. only
at a threshold in the sense of `Emergence.lean`.  New multiplets do not appear
between thresholds.

**Honest limit.**  None of this predicts *which* multiplets.  It says where
they may change and that they are internally flat.  The scale pattern is still
an input.
-/
import SCD.Connection
import SCD.Coupling
import SCD.Gauge
import SCD.Emergence

namespace SCD.Dynamics

open SCD Quantum Connection ScaleAlgebra

/-! ## I. Commuting directions do not make anything flat -/

variable {n : ℕ} {M : Type*} [Ring M] [ScaleAlgebra n M]

/-- **Killing the derivations does not flatten the curvature.**

Take the directions to be as commuting as they can possibly be — every
derivation zero.  The curvature is still `ad (A i) (A j)`, entirely free.

This withdraws `Direction.lean`'s claim that A1's `d_comm` was a hidden
flatness assumption.  `d_comm` says the chart is a chart.  Flatness is a
statement about the *connection*. -/
theorem no_flatness_from_commuting_derivations (A : Fin n → M)
    (hD : ∀ (i : Fin n) (x : M), d i x = 0) (i j : Fin n) :
    F A i j = ad (A i) (A j) := by
  simp only [F, hD, sub_self, zero_add]

/-- And the remaining term is genuinely nonzero: the two directional scalings of
`Coupling.lean` have `ad K₁ K₂ = J ≠ 0`.

So there is a connection with perfectly commuting directions and nonvanishing
curvature.  The claim being withdrawn is refuted by a witness, not weakened. -/
theorem nonflat_witness :
    ad Coupling.K₁ Coupling.K₂ = Coupling.J ∧ (Coupling.J : Matrix (Fin 3) (Fin 3) ℝ) ≠ 0 := by
  constructor
  · -- `Coupling.br` *is* `ad`: one construction, evaluated on scalings here and
    -- on transports in `Connection.lean`.
    rw [show ad Coupling.K₁ Coupling.K₂ = Coupling.br Coupling.K₁ Coupling.K₂ from rfl,
      Coupling.boost_bracket_eq_rotation]
  · intro h
    have h12 : (Coupling.J : Matrix (Fin 3) (Fin 3) ℝ) 1 2 = 0 := by rw [h]; rfl
    simp [Coupling.J] at h12

/-! ### What the commutative sector actually costs

Not quantum non-commutativity — that lives in the transports, which are
non-commutative throughout.  What it costs is transport curvature. -/

/-- **Over a commutative ring the transports commute.**

`ad` vanishes identically, so `comm_covD` returns zero: the sector has no
curvature in the transport sense whatever the connection is.

This is exactly why `Conformal.lean` has to postulate `δ` and get its curvature
from the conformal factor rather than from the connection.  The cost of the
commutative sector is stated here in full, and it is confined to the classical
isotropic geometry. -/
theorem commutative_sector_transports_commute {C : Type*} [CommRing C] [ScaleAlgebra n C]
    (A : Fin n → C) (i j : Fin n) (m : C) :
    covD A i (covD A j m) - covD A j (covD A i m) = 0 := by
  rw [comm_covD]
  simp only [ad, mul_comm, sub_self]

/-- Restated as the diagnosis: in the commutative sector the curvature acts
trivially on everything, so no transport can detect it. -/
theorem commutative_curvature_undetectable {C : Type*} [CommRing C] [ScaleAlgebra n C]
    (A : Fin n → C) (i j : Fin n) (m : C) : ad (F A i j) m = 0 := by
  simp only [ad, mul_comm, sub_self]

/-! ## II. The evolution equation, and why conservation is not a postulate -/

/-- **Bianchi forces the source to be conserved.**

Suppose the scale field's curvature is proportional to a source — the shape of
any field equation.  Then the cyclic covariant divergence of that source
vanishes identically, because `Connection.bianchi` says so of the curvature.

Conservation is therefore not an extra law laid alongside the field equation.
It is a consequence of the field equation's *existence*, and its origin is the
Jacobi identity for `ad`: the associativity of transport. -/
theorem source_conserved_of_field_equation (A : Fin n → M) (κ : M) (T : Fin n → Fin n → M)
    (hfield : ∀ i j, F A i j = κ * T i j) (i j k : Fin n) :
    covD A i (κ * T j k) + covD A j (κ * T k i) + covD A k (κ * T i j) = 0 := by
  rw [← hfield j k, ← hfield k i, ← hfield i j]
  exact bianchi A i j k

/-- **The sharp form: a non-conserved source admits no field equation.**

If the cyclic divergence of `κT` fails to vanish anywhere, then `κT` cannot be
the source of *any* connection's curvature.  The framework does not merely
prefer conserved sources; it cannot express non-conserved ones. -/
theorem no_field_equation_of_nonconserved (A : Fin n → M) (κ : M) (T : Fin n → Fin n → M)
    (i j k : Fin n)
    (hnc : covD A i (κ * T j k) + covD A j (κ * T k i) + covD A k (κ * T i j) ≠ 0) :
    ¬ (∀ i j, F A i j = κ * T i j) := by
  intro hfield
  exact hnc (source_conserved_of_field_equation A κ T hfield i j k)

/-- The source inherits the curvature's antisymmetry, so it is a two-form and
not an arbitrary tensor.  Combined with `Coupling.bracket_scaling_scaling`,
which makes the curvature rotation-valued, **what sources the scale field is a
rotation density**. -/
theorem source_antisymm (A : Fin n → M) (κ : M) (T : Fin n → Fin n → M)
    (hfield : ∀ i j, F A i j = κ * T i j) (i j : Fin n) :
    κ * T i j = -(κ * T j i) := by
  rw [← hfield i j, ← hfield j i]
  exact F_antisymm A i j

/-- Collected: the field equation, if writable at all, carries its own
conservation law and its own antisymmetry.  Neither was put in. -/
theorem field_equation_content (A : Fin n → M) (κ : M) (T : Fin n → Fin n → M)
    (hfield : ∀ i j, F A i j = κ * T i j) (i j k : Fin n) :
    (covD A i (κ * T j k) + covD A j (κ * T k i) + covD A k (κ * T i j) = 0)
    ∧ (κ * T i j = -(κ * T j i)) :=
  ⟨source_conserved_of_field_equation A κ T hfield i j k, source_antisymm A κ T hfield i j⟩

/-! ## III. Multiplets are internally flat

`Gauge.lean`: a multiplet is a degeneracy block of the directional scale.
`Coupling.lean`: a scaling brackets to zero with itself.  Together they say
where curvature can be generated. -/

section Multiplets

variable {N : ℕ} {A : Type*} [CommRing A] [DecidableEq (Fin N)]
variable {m : Type*} [Fintype m] [DecidableEq m]

/-- A scale pattern assigns each direction its scaling operator.  Directions
carrying the same local unit scale the same way — that is what "same unit"
means, so it is a definition rather than an assumption. -/
def Realizes (s : Fin N → Aˣ) (S : Fin N → Matrix m m ℝ) : Prop :=
  ∀ a b, s a = s b → S a = S b

/-- **Two directions in the same multiplet generate no rotation.**

They carry the same unit, hence the same scaling, and a scaling brackets to
zero with itself.  So a degeneracy block of the scale is **internally flat**:
curvature is generated only *between* multiplets.

This is the coupling doing work.  Before it, `Gauge.lean`'s multiplets and
`Connection.lean`'s curvature were two unrelated readings of the scale pattern.
Now the first controls the second. -/
theorem same_multiplet_no_rotation (s : Fin N → Aˣ) (S : Fin N → Matrix m m ℝ)
    (hR : Realizes s S) {a b : Fin N} (hab : Gauge.SameOrbit s a b) :
    Coupling.br (S a) (S b) = 0 := by
  have hs : s a = s b := (Gauge.sameOrbit_iff_eq_scale s a b).mp hab
  rw [hR a b hs]
  exact Coupling.bracket_self (S b)

/-- Equivalently: a nonzero rotation between two directions proves they are in
**different** multiplets.  Curvature is a witness of broken degeneracy. -/
theorem rotation_implies_different_multiplet (s : Fin N → Aˣ) (S : Fin N → Matrix m m ℝ)
    (hR : Realizes s S) {a b : Fin N} (h : Coupling.br (S a) (S b) ≠ 0) :
    ¬ Gauge.SameOrbit s a b := fun hab => h (same_multiplet_no_rotation s S hR hab)

omit [DecidableEq (Fin N)] in
/-- **More symmetry, less structure.**

If the scale is fully degenerate — every direction the same unit, the isotropic
case — then every bracket vanishes and no rotation is generated anywhere.  The
maximally symmetric configuration is the flat one.

This recovers `Frame.isotropic_reciprocal_forces_flat` and
`Connection.curv_pure_scale_eq_zero` from the gauge side, which is a third
independent route to the same fact. -/
theorem larger_multiplet_fewer_generators (s : Fin N → Aˣ) (S : Fin N → Matrix m m ℝ)
    (hR : Realizes s S) (hiso : ∀ a b, s a = s b) (a b : Fin N) :
    Coupling.br (S a) (S b) = 0 := by
  rw [hR a b (hiso a b)]
  exact Coupling.bracket_self (S b)

/-- **Multiplet structure can change only where the scale pattern changes.**

Since the internal symmetry is entirely determined by the pattern of
coincidences among the directional scales, two scales with the same coincidence
pattern have the same multiplets.  So no new multiplet appears without a change
in the pattern — that is, not between thresholds. -/
theorem multiplets_fixed_by_pattern (s t : Fin N → Aˣ)
    (h : ∀ a b, (s a = s b) ↔ (t a = t b)) (a b : Fin N) :
    Gauge.SameOrbit s a b ↔ Gauge.SameOrbit t a b :=
  Gauge.internal_symmetry_determined s t h a b

/-- The contrapositive, which is the statement with content: **a change in
multiplet structure requires a change in the degeneracy pattern**, hence a
threshold.  Combined with `Emergence.content_changes_only_at_threshold`, new
multiplets and new content appear at the same places. -/
theorem multiplet_change_needs_pattern_change (s t : Fin N → Aˣ)
    (hne : ∃ a b, ¬(Gauge.SameOrbit s a b ↔ Gauge.SameOrbit t a b)) :
    ∃ a b, ¬((s a = s b) ↔ (t a = t b)) := by
  by_contra hcon
  push Not at hcon
  obtain ⟨a, b, hab⟩ := hne
  exact hab (multiplets_fixed_by_pattern s t (fun a b => hcon a b) a b)

end Multiplets

end SCD.Dynamics
