/-
# The arrow of time from finite resolution

Nothing in the substrate distinguishes a direction of time: the microscopic
dynamics is a bijection.  What breaks the symmetry is that *observation
happens at a scale*.  A6 says the universe is open and dissipating, so the
scale is always moving; and a scale carries a finite resolution, which is a
non-injective map from micro-configurations to what is distinguishable.

We prove two things.

* **H-theorem.** Under reversible microscopic dynamics followed by
  coarse-graining, the number of micro-configurations consistent with what is
  observed never decreases.  Entropy production is exact bookkeeping, not a
  statistical assumption.

* **Irreversibility.** If entropy strictly increases even once, then *no*
  entropy-non-decreasing law can undo the evolution.  The macroscopic
  equation is therefore not time-reversal invariant even though the
  microscopic one is.  This is precisely the status of the Boltzmann equation.

Both are statements about cardinalities of finite sets, and both are proved
without any probabilistic input.
-/
import Mathlib.Data.Finset.Card
import Mathlib.Data.Fintype.Perm

namespace SCD.Entropy

open Finset

variable {X Y : Type*} [Fintype X] [DecidableEq X] [DecidableEq Y]

/-! ## Coarse-graining: what a finite resolution can distinguish -/

/-- The **saturation** of a set of micro-configurations: everything that the
resolution `π` cannot tell apart from something in `S`.  This is the macrostate
generated by `S`. -/
def sat (π : X → Y) (S : Finset X) : Finset X :=
  Finset.univ.filter (fun x => π x ∈ S.image π)

theorem mem_sat {π : X → Y} {S : Finset X} {x : X} :
    x ∈ sat π S ↔ π x ∈ S.image π := by
  simp [sat]

/-- Coarse-graining never loses a configuration. -/
theorem subset_sat (π : X → Y) (S : Finset X) : S ⊆ sat π S := by
  intro x hx
  rw [mem_sat]
  exact Finset.mem_image_of_mem π hx

theorem card_le_card_sat (π : X → Y) (S : Finset X) : S.card ≤ (sat π S).card :=
  Finset.card_le_card (subset_sat π S)


/-! ## Reversible microdynamics -/

/-- Microscopic evolution is a bijection: no information is created or
destroyed at the level of the substrate. -/
theorem card_image_perm (T : Equiv.Perm X) (S : Finset X) : (S.image T).card = S.card :=
  Finset.card_image_of_injective S T.injective

/-- One step of *observed* evolution: evolve microscopically, then read off at
the available resolution. -/
def evolve (π : X → Y) (T : Equiv.Perm X) (S : Finset X) : Finset X :=
  sat π (S.image T)

/-- **H-theorem.**  Observed entropy — the log of the number of
micro-configurations compatible with the observation — never decreases.

The microscopic step preserves cardinality exactly; the coarse-graining step
can only enlarge.  Nothing statistical is invoked. -/
theorem entropy_nondecreasing (π : X → Y) (T : Equiv.Perm X) (S : Finset X) :
    S.card ≤ (evolve π T S).card := by
  calc S.card = (S.image T).card := (card_image_perm T S).symm
    _ ≤ (sat π (S.image T)).card := card_le_card_sat π _
    _ = (evolve π T S).card := rfl

/-! ## Irreversibility of the macroscopic law

The microscopic law `T` is invertible.  The observed law `evolve` need not be —
and once entropy strictly increases anywhere, it provably is not, in the strong
sense that no law obeying the same H-theorem can serve as its inverse. -/

/-- **The arrow of time.**

Let `F` be any evolution obeying the H-theorem which strictly produces entropy
somewhere.  Then there is no evolution `G`, *also* obeying the H-theorem, with
`G ∘ F = id`.

So the macroscopic equation cannot be run backwards by a law of its own kind.
Time-reversal invariance is lost at the observed level while holding exactly at
the microscopic level — which is the precise sense in which the Boltzmann
equation is irreversible although the mechanics beneath it is not. -/
theorem no_reverse_law (F G : Finset X → Finset X)
    (hG : ∀ S, S.card ≤ (G S).card)
    (hinv : ∀ S, G (F S) = S)
    (S₀ : Finset X) (hstrict : S₀.card < (F S₀).card) : False := by
  have h1 : (F S₀).card ≤ (G (F S₀)).card := hG (F S₀)
  rw [hinv S₀] at h1
  exact absurd h1 (not_le.mpr hstrict)

/-- The same conclusion for the concrete observed dynamics. -/
theorem evolve_no_reverse_law (π : X → Y) (T : Equiv.Perm X)
    (G : Finset X → Finset X) (hG : ∀ S, S.card ≤ (G S).card)
    (hinv : ∀ S, G (evolve π T S) = S)
    (S₀ : Finset X) (hstrict : S₀.card < (evolve π T S₀).card) : False :=
  no_reverse_law (evolve π T) G hG hinv S₀ hstrict

/-! ## Departure from equilibrium is permanent

Sakharov's third condition for generating an asymmetry is departure from
thermal equilibrium.  In a closed system that is a fine-tuned episode.  Under
A6 the universe is open and never stops dissipating, so the condition is
*structurally* satisfied rather than accidentally.

We record the two elementary facts that make this precise.  They are
deliberately modest: they establish that the necessary condition holds
permanently, not that any particular observed asymmetry follows. -/

/-- In equilibrium every observable is stationary.  Hence any charge that
changes at all witnesses departure from equilibrium — Sakharov's third
condition, stated contrapositively. -/
theorem charge_change_implies_nonequilibrium {β : Type*} (F : Finset X → Finset X)
    (Q : Finset X → β) (S : Finset X) (h : Q (F S) ≠ Q S) : F S ≠ S := by
  intro hEq
  exact h (by rw [hEq])

/-- Strict entropy production is itself a departure from equilibrium.  With the
H-theorem above, an open dissipating universe therefore satisfies Sakharov's
third condition at every moment at which it produces entropy. -/
theorem entropy_production_implies_nonequilibrium (F : Finset X → Finset X)
    (S : Finset X) (h : S.card < (F S).card) : F S ≠ S := by
  intro hEq
  rw [hEq] at h
  exact absurd h (lt_irrefl _)

end SCD.Entropy
