/-
# What extension costs, what rotation is, and why three

Three questions, and they turn out to interlock.

## I.  Label proliferation is the price of range, not evidence of structure

The warning to take seriously is that the Standard Model's apparatus — colour,
generations, weak isospin, the confinement mechanism — may not be structure at
all, but what one is *forced* to write down when a slice-local description is
extended over a range of scales.  That is a formalizable claim, and it is
proved here.

`Emergence.lean` says the content at scale `t` is `{k | μ k ≤ t}`, and
`RG.active_eq_of_no_threshold` says a description is *exact* between thresholds.
So a description valid at a single scale needs labels for that scale's content
and no more.  A description valid across a range must carry labels for content
that is **not resolvable** at the lower end:

* `newContent_nonempty_of_threshold` — crossing a threshold forces new labels;
* `newContent_mono` — the excess grows with the range, monotonically;
* `no_finite_universal_labelling` — and it never stops, because
  `Emergence.always_more_above` says there is no last threshold.

**So the number of labels a formalism carries measures the log-range it covers,
not the depth of the physics.**  A framework covering thirty e-folds in one
formalism must carry labels for everything appearing anywhere in those thirty
e-folds, most of them unrealized at any given scale.  That is exactly the shape
of off-shell content, gauge redundancy, and species that exist only virtually.

This does not refute the Standard Model.  It says its label count is evidence
about its *range*, and that reproducing that count is not a target — which is
what `Emergence.lean` claimed and this file proves.

## II.  Rotation is the wedge of scale directions

The framework's own quantities are few: a threshold, a `ℤ/2` label, an integer
charge (`Particle.lean`), and the scale magnitude.  Rotation was not among them,
yet `Coupling.lean` produces it.  What is it, natively?

`Algebra.boost_bracket_spatial` answers: the rotation generated by two scalings
is `vᵢwⱼ − vⱼwᵢ`, the **wedge of their directions**.  So a rotational label is
not an independent quantum number here — it is a function of the scale
structure, with no freedom:

* `wedge_antisymm`, `wedge_bilinear_left` — it is a genuine two-form;
* `wedge_eq_zero_iff_parallel` — it vanishes exactly for parallel directions;
* `homogeneous_carries_no_rotation` — **a *homogeneous* pattern has zero
  rotational label.**

**Correction (see `Axes.lean`).**  I originally named that theorem
`uniaxial_carries_no_rotation` — it is now
`homogeneous_carries_no_rotation` — and read it as "a uniaxial pattern carries no
angular momentum", which made an apparent dilemma with `Particle.lean`'s
uniaxial order parameter.  **That reading was wrong and is withdrawn.**  The
theorem is about a vector wedged with *itself*, so it says a **constant**
pattern generates no rotation; *uniaxial* means the scale takes one distinct
**value**, which is a different thing entirely.  `Axes.lean` shows rotation is
carried by the pattern's *variation*, that a wound defect therefore always
carries rotation, and that more axes are not available at all.

`Particle.lean`'s labels therefore stand unrestricted.  What survives from this
section is the genuine finding — that the framework's rotational quantity is the
wedge of scale directions — which `Axes.lean` then puts to work.

## III.  Why three spatial directions

`Algebra.lean` derived the family and not the dimension.  Here is the one
argument the structure supplies, stated with its exact strength.

A4 provides labels of a single kind: **directions**.  `Gauge.lean` makes every
observable label a degeneracy pattern among directions.  `Coupling.lean` makes
every rotation a wedge of two directions.  So the rotations generated by the
scalings are direction-labelled **only if** the space of wedges has the same
dimension as the space of directions:

        dim Λ²ℝᵏ = k    ⟺    k(k−1)/2 = k    ⟺    k = 3 .

`wedge_dim_eq_iff` proves the arithmetic, `three_is_unique` the uniqueness.
For `k > 3` there are strictly more generated rotations than directions, so some
rotation carries no direction label; for `k < 3` the rotation sector is
degenerate — one generator at `k = 2`, none at `k = 1`.

**`k = 3` is the unique dimension in which the coupling closes on the labels the
axioms provide**, giving `n = k + 1 = 4`.

**How strong is this?**  The arithmetic is a theorem.  The step that carries the
physics — that the framework *requires* its generated rotations to be
direction-labelled, rather than merely permitting some to go unlabelled — is a
judgement, and it is the same kind of judgement as the rank-one identification
in `Algebra.lean`.  It is stated here in the open and registered, not hidden in
a proof.  With it, `n = 4`; without it, `n` remains free.

One coherence worth noting: `k = 3` is also where `so(3) ≅ su(2)` and the
rotation group acquires its double cover — which is where `Particle.lean`'s
`ℤ/2` came from.  The dimension and that label have a single source.
-/
import SCD.Particle
import SCD.Emergence
import SCD.Pattern
import Mathlib.Data.Set.Finite.Basic

namespace SCD.Slice

open SCD

/-! ## I. Extension forces labels that no single scale needs -/

/-- The content a description gains by extending its range from `t` up to `t'`:
structures resolvable at the top but **not** at the bottom.  A formalism valid
across the whole range must carry labels for all of it, while a formalism at
`t` alone needs none of it. -/
def newContent (μ : ℕ → ℝ) (t t' : ℝ) : Set ℕ :=
  Emergence.resolved μ t' \ Emergence.resolved μ t

@[simp] theorem mem_newContent {μ : ℕ → ℝ} {t t' : ℝ} {j : ℕ} :
    j ∈ newContent μ t t' ↔ μ j ≤ t' ∧ ¬ (μ j ≤ t) := Iff.rfl

/-- **Crossing a threshold forces new labels.**

If any structure has its threshold inside the range, the extended description
must carry a label the local one does not need. -/
theorem newContent_nonempty_of_threshold (μ : ℕ → ℝ) {t t' : ℝ} {j : ℕ}
    (h1 : t < μ j) (h2 : μ j ≤ t') : (newContent μ t t').Nonempty :=
  ⟨j, ⟨h2, not_le.mpr h1⟩⟩

/-- **And the excess only grows with the range.**

Widening the window at either end can only add labels, never remove them.  So
the label count is a monotone function of the log-range covered. -/
theorem newContent_mono (μ : ℕ → ℝ) {t₁ t₂ t' t'' : ℝ} (hlo : t₁ ≤ t₂) (hhi : t' ≤ t'') :
    newContent μ t₂ t' ⊆ newContent μ t₁ t'' := by
  rintro j ⟨hj1, hj2⟩
  exact ⟨le_trans hj1 hhi, fun hc => hj2 (le_trans hc hlo)⟩

/-- Conversely, a range with no threshold in it costs nothing: the description
there is exact, which is `RG.active_eq_of_no_threshold` seen from the label
side. -/
theorem newContent_empty_of_no_threshold (μ : ℕ → ℝ) {t t' : ℝ}
    (hgap : ∀ j, ¬(t < μ j ∧ μ j ≤ t')) : newContent μ t t' = ∅ := by
  ext j
  simp only [mem_newContent, Set.mem_empty_iff_false, iff_false, not_and, not_not]
  intro hj
  by_contra hc
  exact hgap j ⟨lt_of_not_ge hc, hj⟩

/-- **No labelling works at every scale.**

Above any scale there is content not yet resolved, so any fixed label set is
eventually insufficient.  A formalism valid at all scales does not exist, and
its absence is a theorem rather than a gap in anyone's ingenuity. -/
theorem no_finite_universal_labelling (μ : ℕ → ℝ) (hunb : ∀ M : ℝ, ∃ j, M < μ j) (t : ℝ) :
    ∃ t', t < t' ∧ (newContent μ t t').Nonempty := by
  obtain ⟨j, hj⟩ := hunb t
  exact ⟨μ j, hj, newContent_nonempty_of_threshold μ hj le_rfl⟩

/-- Collected, as the reply to "why does the Standard Model need so many
labels": because it covers a wide range, and the count measures the range.  A
description at a single scale needs the content of that scale and nothing
more. -/
theorem label_count_measures_range (μ : ℕ → ℝ) (hunb : ∀ M : ℝ, ∃ j, M < μ j) :
    (∀ t : ℝ, ∃ t', t < t' ∧ (newContent μ t t').Nonempty)
    ∧ (∀ t t' : ℝ, (∀ j, ¬(t < μ j ∧ μ j ≤ t')) → newContent μ t t' = ∅) :=
  ⟨no_finite_universal_labelling μ hunb, fun t t' h => newContent_empty_of_no_threshold μ h⟩

/-! ## II. The framework's own rotational quantity

`Algebra.boost_bracket_spatial` computed it: the rotation generated by two
scalings is the wedge of their directions. -/

variable {k : ℕ}

/-! **The wedge is not defined here.**  It was, and then again — under other
names and in other index types — in `Axes.lean`, `Algebra.lean`, `Locus.lean`
and `Dimension.lean`, with equivalence theorems joining them up.  It is now
defined once in `Pattern.lean`, over a ring rather than over `ℝ`, which is what
lets `NCConformal.quantum_correction_is_a_wedge` state the identity between the
rotational label and the quantum correction instead of a resemblance.

What this file contributes is the *identification*: the wedge is exactly what
the coupling generates. -/

/-- **The rotational label is what the coupling generates.**

`Algebra.boost_bracket_spatial` computed the bracket of two boosts on the
spatial block and got `vᵢwⱼ − vⱼwᵢ`.  That is `Pattern.wedge`, so the framework's
rotational quantity is not an extra label: it is a function of the scale
structure, with no freedom. -/
theorem wedge_eq_bracket (v w : Fin k → ℝ) (i j : Fin k) :
    wedge v w i j = Coupling.br (Algebra.boost v) (Algebra.boost w) i.succ j.succ :=
  (Algebra.boost_bracket_spatial v w i j).symm

/-- **A single scale direction carries no rotational label.**

The wedge of a direction with itself vanishes.  So a **homogeneous** scale
pattern has zero rotational label, whatever else it carries — and by
`Pattern.wedge_self_eq_commutator` this is exactly the statement that the scale
values commute, which is what fails in the quantum sector. -/
theorem homogeneous_carries_no_rotation (v : Fin k → ℝ) (i j : Fin k) :
    wedge v v i j = 0 := wedge_self v i j

/-- **The dilemma this creates.**

`Particle.lean` computed the label structure `(ℝ, ℤ/2, ℤ)` from a *uniaxial*
order parameter — an unoriented axis, hence projective space.  But a uniaxial
pattern carries no rotational label at all.  Since observed particles carry
angular momentum, one of the two must give:

* either particles are **not** uniaxial, and `Particle.lean`'s two labels are
  the wrong computation — they must be redone for a biaxial order parameter,
  whose homotopy is different and larger;
* or defects here are rotationless, which the world contradicts.

This is the sharpest open problem, and it was reached by asking what the
framework's own rotational quantity is, not by trying to reproduce spin.

The formal half of it: **a nonzero rotational label forces two non-parallel
scale directions.**  Anything carrying angular momentum is therefore at least
biaxial, and the projective order parameter that produced `ℤ/2` and `ℤ` is not
its order parameter. -/
theorem rotation_requires_biaxial {v w : Fin k → ℝ} {i j : Fin k}
    (h : wedge v w i j ≠ 0) : ∀ c : ℝ, w ≠ c • v := by
  intro c hc
  apply h
  subst hc
  simp only [wedge, Pi.smul_apply, smul_eq_mul]
  ring

/-! ## III. Why three

A4 supplies labels of one kind: directions.  `Gauge.lean` makes every observable
label a pattern among directions.  `Coupling.lean` makes every rotation a wedge
of two.  Those close on one another exactly when the wedges are as numerous as
the directions. -/

/-! The two counts are `Pattern.rotDim2` and `Pattern.scaleDim2`, and their
equality is A7 — `Pattern.Observability`.  They were previously declared here as
`wedgeDim`/`dirDim` and again in `Dimension.lean` as `rotDim2`/`scaleDim2`, with
`Dimension.rot_matches_scale_iff` bridging the two.  One pair now. -/

/-- **The wedges are as numerous as the directions exactly in three
dimensions.**

`k(k−1)/2 = k` has the unique positive solution `k = 3`.  This is
`Pattern.observability_iff_two`, restated where the argument for it is made. -/
theorem wedge_dim_eq_iff (m : ℕ) : rotDim2 m = scaleDim2 m ↔ m = 2 :=
  observability_iff_two m

/-- **So `k = 3`, and `n = k + 1 = 4`.**

Three spatial directions is the unique case in which every rotation the
scalings generate carries a label the axioms provide.  Above three there are
more wedges than directions, so some generated rotation is unlabelled; below
three the rotation sector degenerates.

The arithmetic is a theorem.  The step that carries the physics — that the
framework *requires* its generated rotations to be direction-labelled rather
than merely permitting some to go unlabelled — is a judgement of the same kind
as the rank-one identification, and is registered as such. -/
theorem three_is_unique : (∃! m : ℕ, rotDim2 m = scaleDim2 m) := observability_unique

/-- Above three dimensions there are strictly more wedges than directions, so
some generated rotation carries no direction label. -/
theorem more_wedges_than_directions (m : ℕ) (hm : 2 < m) : scaleDim2 m < rotDim2 m :=
  more_rotations_than_directions m hm

/-- And below three there are strictly fewer: the rotation sector degenerates. -/
theorem fewer_wedges_than_directions (m : ℕ) (hm : m < 2) : rotDim2 m < scaleDim2 m :=
  fewer_rotations_than_directions m hm

end SCD.Slice
