/-
# Verification — every theorem, through `#print axioms`

Not part of the library: `SCD.lean` does not import it.  It imports `SCD` and
puts **every** theorem in the development through `#print axioms`, in the
reading order of the root file.

Generated by `tools/sync_report.py` from the sources, not curated, so nothing
can quietly fall out of the audit.  A clean run prints only `propext`,
`Classical.choice` and `Quot.sound`, and never `sorryAx`.
-/
import SCD

namespace SCD.Verify


/-! ## PART 0 — the postulates -/


-- Pattern.lean
#print axioms SCD.IsIsotropic.const
#print axioms SCD.IsIsotropic.map
#print axioms SCD.IsIsotropic.eq_const
#print axioms SCD.IsIsotropic.iff_exists_const
#print axioms SCD.IsIsotropic
#print axioms SCD.parallel_self
#print axioms SCD.Parallel
#print axioms SCD.wedge_self_index
#print axioms SCD.wedge_antisymm
#print axioms SCD.wedge_self_eq_commutator
#print axioms SCD.wedge_bilinear_left
#print axioms SCD.wedge_eq_zero_iff_parallel
#print axioms SCD.not_parallel_of_wedge_ne_zero
#print axioms SCD.wedge_ne_zero_of_ne
#print axioms SCD.wedge_eq_zero_of_isotropic
#print axioms SCD.wedge_self
#print axioms SCD.wedge_swap
#print axioms SCD.wedge_smul_both
#print axioms SCD.wedge_smul_smul
#print axioms SCD.wedge_rescale
#print axioms SCD.wedge_rescale_ne_zero
#print axioms SCD.observability_iff_two
#print axioms SCD.three_from_observability
#print axioms SCD.observability_fails_elsewhere
#print axioms SCD.observability_unique
#print axioms SCD.more_rotations_than_directions
#print axioms SCD.fewer_rotations_than_directions

-- Basic.lean
#print axioms SCD.ScaleAlgebra.d_zero
#print axioms SCD.ScaleAlgebra.d_one
#print axioms SCD.ScaleAlgebra.d_neg
#print axioms SCD.ScaleAlgebra.d_sub
#print axioms SCD.ScaleAlgebra.d_sum
#print axioms SCD.ScaleAlgebra.d_natCast
#print axioms SCD.ScaleAlgebra.d_nsmul
#print axioms SCD.kron_self
#print axioms SCD.kron_symm
#print axioms SCD.kron_comm
#print axioms SCD.kron_swap
#print axioms SCD.kron_mul_kron_mul
#print axioms SCD.sum_kron_left
#print axioms SCD.sum_kron_right
#print axioms SCD.sum_const_fin
#print axioms SCD.d_kron
#print axioms SCD.d_kron_mul

-- Axioms.lean
#print axioms SCD.ScaleField.en_mul_scale
#print axioms SCD.ScaleField.scale_mul_en
#print axioms SCD.ScaleField.d_en
#print axioms SCD.ScaleField.ext
#print axioms SCD.ScaleField.mul_σ
#print axioms SCD.ScaleField.mul_s
#print axioms SCD.ScaleField.inv_σ
#print axioms SCD.ScaleField.inv_s
#print axioms SCD.ScaleField.one_σ
#print axioms SCD.ScaleField.one_s
#print axioms SCD.ScaleField.en_eq_inv_s
#print axioms SCD.ScaleField.scale_energy_duality_is_inversion
#print axioms SCD.ScaleField.inv_inv_eq
#print axioms SCD.ScaleField.en_mul
#print axioms SCD.ScaleField.mem_fiducials
#print axioms SCD.ScaleField.sig_mul_fiducial
#print axioms SCD.ScaleField.en_mul_fiducial
#print axioms SCD.sig_add_const
#print axioms SCD.hess_add_const
#print axioms SCD.lap_add_const
#print axioms SCD.gradsq_add_const
#print axioms SCD.Chr_add_const
#print axioms SCD.Rm_add_const
#print axioms SCD.Ric_add_const
#print axioms SCD.Defm_add_const
#print axioms SCD.geometry_fiducial_invariant
#print axioms SCD.sig_neg
#print axioms SCD.hess_neg
#print axioms SCD.lap_neg
#print axioms SCD.gradsq_neg

-- Postulates.lean
#print axioms SCD.Postulates.substrate_hessian_symm
#print axioms SCD.Postulates.commutative_sector_is_the_substrate
#print axioms SCD.Postulates.three_from_A7
#print axioms SCD.Postulates.A7_holds_only_at_three

/-! ## PART I — what the axioms force -/


-- Foundation.lean
#print axioms SCD.Foundation.scale_mul
#print axioms SCD.Foundation.scale_comm
#print axioms SCD.Foundation.scale_inv
#print axioms SCD.Foundation.scale_commutator
#print axioms SCD.Foundation.curvature_is_scale_invisible
#print axioms SCD.Foundation.scale_eq_one_of_mem_commutator
#print axioms SCD.Foundation.mem_commutator_of_scale_eq_one
#print axioms SCD.Foundation.scale_eq_iff_differ_by_rotation
#print axioms SCD.Foundation.commutator_eq_one_of_comm
#print axioms SCD.Foundation.comm_of_scale_injective

-- Signature.lean
#print axioms SCD.Signature.codim_ker_eq_one
#print axioms SCD.Signature.no_time_of_no_drift
#print axioms SCD.Signature.spatial_eq_top_of_no_drift
#print axioms SCD.Signature.spatial_ne_top_of_drift
#print axioms SCD.Signature.drift_direction_unique
#print axioms SCD.Signature.spatial_smul
#print axioms SCD.Signature.signature_from_dissipation

-- Invariant.lean
#print axioms SCD.Invariant.Trace.map_zero
#print axioms SCD.Invariant.Trace.map_sub
#print axioms SCD.Invariant.Trace.form_symm
#print axioms SCD.Invariant.Trace.form_invariant
#print axioms SCD.Invariant.Trace.form_ad_skew
#print axioms SCD.Invariant.Trace.form_commutator_self

-- Quantum.lean
#print axioms SCD.Quantum.ad_zero_left
#print axioms SCD.Quantum.ad_leibniz
#print axioms SCD.Quantum.ad_jacobi
#print axioms SCD.Quantum.ad_comm_of_commute
#print axioms SCD.Quantum.ad_pow
#print axioms SCD.Quantum.robertson
#print axioms SCD.Quantum.heisenberg

-- Direction.lean
#print axioms SCD.Direction.DirTransport.D_zero_dir
#print axioms SCD.Direction.DirTransport.D_neg_dir
#print axioms SCD.Direction.DirTransport.curv_self
#print axioms SCD.Direction.DirTransport.curv_antisymm
#print axioms SCD.Direction.DirTransport.flat_iff_lie_hom
#print axioms SCD.Direction.DirTransport.curv_of_abelian
#print axioms SCD.Direction.DirTransport.commute_iff_bracket_acts_trivially
#print axioms SCD.Direction.DirTransport.transport_determined_by_generators

-- Connection.lean
#print axioms SCD.Connection.F_antisymm
#print axioms SCD.Connection.comm_covD
#print axioms SCD.Connection.bianchi
#print axioms SCD.Connection.curv_of_central
#print axioms SCD.Connection.curv_gradient_eq_zero
#print axioms SCD.Connection.curv_split
#print axioms SCD.Connection.curv_eq_rotation_part
#print axioms SCD.Connection.curv_pure_scale_eq_zero

-- Coupling.lean
#print axioms SCD.Coupling.br_eq_ad
#print axioms SCD.Coupling.bracket_scaling_scaling
#print axioms SCD.Coupling.bracket_rotation_scaling
#print axioms SCD.Coupling.bracket_rotation_rotation
#print axioms SCD.Coupling.coupling_structure
#print axioms SCD.Coupling.bracket_self
#print axioms SCD.Coupling.no_rotation_of_commuting
#print axioms SCD.Coupling.boost_bracket_eq_rotation
#print axioms SCD.Coupling.scalings_do_not_commute

-- Algebra.lean
#print axioms SCD.Algebra.scaling_rotation_orthogonal
#print axioms SCD.Algebra.boost_zero_zero
#print axioms SCD.Algebra.boost_zero_succ
#print axioms SCD.Algebra.boost_succ_zero
#print axioms SCD.Algebra.boost_succ_succ
#print axioms SCD.Algebra.boost_isScaling
#print axioms SCD.Algebra.boost_add
#print axioms SCD.Algebra.boost_smul
#print axioms SCD.Algebra.boost_mul_succ_succ
#print axioms SCD.Algebra.boost_bracket_spatial
#print axioms SCD.Algebra.boosts_commute_iff_parallel
#print axioms SCD.Algebra.commuting_boosts_lie_on_a_line
#print axioms SCD.Algebra.commuting_family_one_parameter
#print axioms SCD.Algebra.no_two_dimensional_commuting_family
#print axioms SCD.Algebra.boosts_commute_iff_no_wedge
#print axioms SCD.Algebra.boost_drift
#print axioms SCD.Algebra.commuting_drifts_proportional
#print axioms SCD.Algebra.boost_spatial_block_zero
#print axioms SCD.Algebra.boost_eq_zero_iff

-- Dimension.lean
#print axioms SCD.Dimension.algebra_bigger_than_directions
#print axioms SCD.Dimension.rep_dim_determined
#print axioms SCD.Dimension.rot_matches_scale_iff
#print axioms SCD.Dimension.alg_matches_rep_iff
#print axioms SCD.Dimension.two_matching_conditions_differ
#print axioms SCD.Dimension.wedge_ratio_invariant
#print axioms SCD.Dimension.only_ratios_are_fixed
#print axioms SCD.Dimension.density_normalization_relation
#print axioms SCD.Dimension.normalization_returns_input

-- Slice.lean
#print axioms SCD.Slice.mem_newContent
#print axioms SCD.Slice.newContent_nonempty_of_threshold
#print axioms SCD.Slice.newContent_mono
#print axioms SCD.Slice.newContent_empty_of_no_threshold
#print axioms SCD.Slice.no_finite_universal_labelling
#print axioms SCD.Slice.label_count_measures_range
#print axioms SCD.Slice.wedge_eq_bracket
#print axioms SCD.Slice.homogeneous_carries_no_rotation
#print axioms SCD.Slice.rotation_requires_biaxial
#print axioms SCD.Slice.wedge_dim_eq_iff
#print axioms SCD.Slice.three_is_unique
#print axioms SCD.Slice.more_wedges_than_directions
#print axioms SCD.Slice.fewer_wedges_than_directions

-- Axes.lean
#print axioms SCD.Axes.rotation_needs_variation
#print axioms SCD.Axes.combable_no_rotation
#print axioms SCD.Axes.wound_carries_rotation
#print axioms SCD.Axes.rotationless_is_trivial
#print axioms SCD.Axes.rotation_iff_variation
#print axioms SCD.Axes.no_second_axis
#print axioms SCD.Axes.no_second_axis_eq_rank_one
#print axioms SCD.Axes.axis_or_variation
#print axioms SCD.Axes.axis_stabilizer_nontrivial
#print axioms SCD.Axes.multiplet_flatness_needs_per_direction_scalings

/-! ## PART II — the branch point -/


-- Locus.lean
#print axioms SCD.Locus.A7_gives_three
#print axioms SCD.Locus.observability_iff_three
#print axioms SCD.Locus.no_scale_invariant_interaction
#print axioms SCD.Locus.constant_coupling_iff_no_content
#print axioms SCD.Locus.isotropic_pair_parallel
#print axioms SCD.Locus.isotropic_no_rotation
#print axioms SCD.Locus.labels_require_anisotropy
#print axioms SCD.Locus.everything_switches_on_together
#print axioms SCD.Locus.particle_locus_is_anisotropic

-- Dynamics.lean
#print axioms SCD.Dynamics.no_flatness_from_commuting_derivations
#print axioms SCD.Dynamics.nonflat_witness
#print axioms SCD.Dynamics.commutative_sector_transports_commute
#print axioms SCD.Dynamics.commutative_curvature_undetectable
#print axioms SCD.Dynamics.source_conserved_of_field_equation
#print axioms SCD.Dynamics.no_field_equation_of_nonconserved
#print axioms SCD.Dynamics.source_antisymm
#print axioms SCD.Dynamics.field_equation_content
#print axioms SCD.Dynamics.same_multiplet_no_rotation
#print axioms SCD.Dynamics.rotation_implies_different_multiplet
#print axioms SCD.Dynamics.larger_multiplet_fewer_generators
#print axioms SCD.Dynamics.multiplets_fixed_by_pattern
#print axioms SCD.Dynamics.multiplet_change_needs_pattern_change

-- Determination.lean
#print axioms SCD.Determination.influence_symm
#print axioms SCD.Determination.curvature_is_total_influence
#print axioms SCD.Determination.free_implies_offdiag_zero
#print axioms SCD.Determination.ric_offdiag_symm
#print axioms SCD.Determination.no_influence_in_two
#print axioms SCD.Determination.two_directions_always_free
#print axioms SCD.Determination.determination_well_posed
#print axioms SCD.Determination.over_or_under_determined

-- Explanation.lean
#print axioms SCD.Explanation.not_both
#print axioms SCD.Explanation.predicted_or_modulus
#print axioms SCD.Explanation.value_from_any_solution
#print axioms SCD.Explanation.tightening_predicts_more
#print axioms SCD.Explanation.vacuous_predicts_everything
#print axioms SCD.Explanation.total_predicts_only_constants
#print axioms SCD.Explanation.power_requires_a_witness
#print axioms SCD.Explanation.separable_is_free
#print axioms SCD.Explanation.force_is_non_separability
#print axioms SCD.Explanation.pderiv_comm'
#print axioms SCD.Explanation.d_eq_pderiv
#print axioms SCD.Explanation.coupled_influence
#print axioms SCD.Explanation.coupled_influence_ne_zero
#print axioms SCD.Explanation.coupled_not_free
#print axioms SCD.Explanation.influence_not_homogeneous
#print axioms SCD.Explanation.separated_separable
#print axioms SCD.Explanation.constraint_is_proper
#print axioms SCD.Explanation.self_not_in_determiner
#print axioms SCD.Explanation.determiner_card
#print axioms SCD.Explanation.no_arrow_from_determination
#print axioms SCD.Explanation.cycle_of_three
#print axioms SCD.Explanation.leverage
#print axioms SCD.Explanation.what_it_delivers

-- Anchor.lean
#print axioms SCD.Anchor.factor_two_has_no_failing_instance
#print axioms SCD.Anchor.gamma_claim_is_falsifiable
#print axioms SCD.Anchor.precession_ratio_has_no_failing_instance
#print axioms SCD.Anchor.signed_source_is_distinguished
#print axioms SCD.Anchor.counted_source_is_uniform
#print axioms SCD.Anchor.the_inflation
#print axioms SCD.Anchor.drift_exceeds_anchor
#print axioms SCD.Anchor.honest_ledger

-- Observer.lean
#print axioms SCD.Observer.crossed_fiducial_invariant
#print axioms SCD.Observer.crossedSet_mono
#print axioms SCD.Observer.one_axis_is_a_chain
#print axioms SCD.Observer.two_axes_incomparable
#print axioms SCD.Observer.common_refinement
#print axioms SCD.Observer.incomparable_but_absolute
#print axioms SCD.Observer.aoe_needs_join_failure
#print axioms SCD.Observer.summary

-- Observed.lean
#print axioms SCD.Observed.crossedSet_meet
#print axioms SCD.Observed.agreement_is_an_observer
#print axioms SCD.Observed.observation_is_fiducial_invariant
#print axioms SCD.Observed.drift_monotone
#print axioms SCD.Observed.drift_cannot_resolve
#print axioms SCD.Observed.path_underdetermined
#print axioms SCD.Observed.all_observations_compatible
#print axioms SCD.Observed.observer_cannot_separate_them
#print axioms SCD.Observed.summary

-- Internal.lean
#print axioms SCD.Internal.record_antitone
#print axioms SCD.Internal.record_union
#print axioms SCD.Internal.record_univ_is_the_detached_observer
#print axioms SCD.Internal.observer_is_in_the_determiner
#print axioms SCD.Internal.no_disturbance_of_separable
#print axioms SCD.Internal.disturbance_iff_separable
#print axioms SCD.Internal.internal_observations_still_compatible
#print axioms SCD.Internal.summary

-- Triple.lean
#print axioms SCD.Triple.inf_eq_influence
#print axioms SCD.Triple.influence_asymmetry
#print axioms SCD.Triple.readings_agree_of_comm
#print axioms SCD.Triple.d_mat
#print axioms SCD.Triple.asymmetry_witness
#print axioms SCD.Triple.readings_disagree
#print axioms SCD.Triple.observer_observed_not_symmetric
#print axioms SCD.Triple.summary

-- Mutual.lean
#print axioms SCD.Mutual.influence_sees_the_pair_scales
#print axioms SCD.Mutual.asymmetry_depends_only_on_the_observer
#print axioms SCD.Mutual.triWedge_eq_alternating
#print axioms SCD.Mutual.triWedge_antisymm
#print axioms SCD.Mutual.triWedge_from_dirCommutator
#print axioms SCD.Mutual.triWedge_comm_zero
#print axioms SCD.Mutual.triWedge_isotropic_zero
#print axioms SCD.Mutual.triWedge_witness
#print axioms SCD.Mutual.triWedge_not_identically_zero
#print axioms SCD.Mutual.summary

-- Ordering.lean
#print axioms SCD.Ordering.offDiag_eq_classical
#print axioms SCD.Ordering.integrand_sub_rev
#print axioms SCD.Ordering.offDiag_sub_rev
#print axioms SCD.Ordering.orderings_agree_of_comm
#print axioms SCD.Ordering.crossed_two
#print axioms SCD.Ordering.crossed_zero
#print axioms SCD.Ordering.crossed_one
#print axioms SCD.Ordering.transverse_zero_one
#print axioms SCD.Ordering.vacuum_is_ordering_dependent
#print axioms SCD.Ordering.ordering_irrelevant_of_static
#print axioms SCD.Ordering.sym_is_order_free
#print axioms SCD.Ordering.sym_doubles_the_classical
#print axioms SCD.Ordering.summary

-- Screen.lean
#print axioms SCD.Screen.observer_preserves_predictions
#print axioms SCD.Screen.observer_preserves_predictions_vacuously
#print axioms SCD.Screen.recorded_by_one
#print axioms SCD.Screen.not_recorded_by_zero
#print axioms SCD.Screen.recorded_set_is_observer_relative
#print axioms SCD.Screen.observer_relative_is_modulus
#print axioms SCD.Screen.observer_relative_can_be_modulus
#print axioms SCD.Screen.sample_grows_as_observer_shrinks
#print axioms SCD.Screen.screen_is_exhaustive
#print axioms SCD.Screen.the_discriminating_entry_is_the_observer_relative_one

-- Resolution.lean
#print axioms SCD.Resolution.Filtration.resolved_mono
#print axioms SCD.Resolution.Filtration.not_resolved_zero
#print axioms SCD.Resolution.Filtration.compatible_symm
#print axioms SCD.Resolution.Filtration.compatible_of_le
#print axioms SCD.Resolution.commutative_all_compatible
#print axioms SCD.Resolution.incompatible_witness
#print axioms SCD.Resolution.compatible_at_zero

/-! ## PART II.a — the isotropic sector -/


-- Conformal.lean
#print axioms SCD.hess_symm
#print axioms SCD.d_sig_comm
#print axioms SCD.sum_mul_gradsq
#print axioms SCD.scaleCurv_eq_zero
#print axioms SCD.Chr_symm
#print axioms SCD.d_Chr_diff
#print axioms SCD.sum_d_Chr
#print axioms SCD.sum_Chr_diag
#print axioms SCD.sum_d_Chr_trace
#print axioms SCD.sum_ChrTrace_Chr
#print axioms SCD.sum_Chr_Chr_full
#print axioms SCD.sum_Chr_Chr
#print axioms SCD.Ric_eq
#print axioms SCD.RscBare_eq
#print axioms SCD.Defm_symm
#print axioms SCD.two_Rm_eq
#print axioms SCD.Rm_eq_zero_of_Defm_eq_zero
#print axioms SCD.Ric_eq_zero_of_Defm_eq_zero
#print axioms SCD.two_Ric_eq

-- Frame.lean
#print axioms SCD.Frame.DirScale.en_mul_scale
#print axioms SCD.Frame.DirScale.scale_mul_en
#print axioms SCD.Frame.DirScale.isotropic_iff
#print axioms SCD.Frame.DirScale.isotropic_metric
#print axioms SCD.Frame.DirScale.isotropic_en
#print axioms SCD.Frame.DirScale.reciprocal_iff_radial_is_temporal_energy
#print axioms SCD.Frame.DirScale.reciprocal_symm
#print axioms SCD.Frame.DirScale.reciprocal_metric
#print axioms SCD.Frame.DirScale.isotropic_reciprocal_forces_flat
#print axioms SCD.Frame.DirScale.isotropic_reciprocal_metric_bare
#print axioms SCD.Frame.exists_reciprocal_nonisotropic

-- Unify.lean
#print axioms SCD.Unify.toMetric_of_isotropic
#print axioms SCD.Unify.ofScalar_isotropic
#print axioms SCD.Unify.ofScalar_toMetric
#print axioms SCD.Unify.isotropic_iff_ofScalar
#print axioms SCD.Unify.toDirScale_isotropic
#print axioms SCD.Unify.toDirScale_toMetric
#print axioms SCD.Unify.sector_coherence
#print axioms SCD.Unify.toDirScale_en
#print axioms SCD.Unify.isotropic_iff_energy_isotropic
#print axioms SCD.Unify.isotropic_ratio_const
#print axioms SCD.Unify.not_isotropic_of_ne

-- Newton.lean
#print axioms SCD.lap_newtPot
#print axioms SCD.RscBare_linear
#print axioms SCD.poisson
#print axioms SCD.poisson_three
#print axioms SCD.Dual.sig_inr
#print axioms SCD.Dual.gradsq_inr
#print axioms SCD.Dual.poisson_exact

-- Diagonal.lean
#print axioms SCD.Diagonal.ratio_self
#print axioms SCD.Diagonal.ratio_mul
#print axioms SCD.Diagonal.kron_subst
#print axioms SCD.Diagonal.metric_compatible
#print axioms SCD.Diagonal.d_ratio
#print axioms SCD.Diagonal.chr_eq_zero
#print axioms SCD.Diagonal.chr_rrr
#print axioms SCD.Diagonal.chr_diag_r
#print axioms SCD.Diagonal.chr_diag_r'
#print axioms SCD.Diagonal.chr_r_aa
#print axioms SCD.Diagonal.trace_chr_r
#print axioms SCD.Diagonal.trace_chr_off
#print axioms SCD.Diagonal.chr_off_tt
#print axioms SCD.Diagonal.ric_tt
#print axioms SCD.Diagonal.ric_rr
#print axioms SCD.Diagonal.sum_split
#print axioms SCD.Diagonal.ric_tt_mixed
#print axioms SCD.Diagonal.combination_is_transverse
#print axioms SCD.Diagonal.combination_areal
#print axioms SCD.Diagonal.vacuum_scale_sum
#print axioms SCD.Diagonal.ratio_inv
#print axioms SCD.Diagonal.chr_gen_diag
#print axioms SCD.Diagonal.chr_gen_off
#print axioms SCD.Diagonal.chr_gen_zero
#print axioms SCD.Diagonal.trace_gen
#print axioms SCD.Diagonal.chr_lower_symm
#print axioms SCD.Diagonal.ric_offdiag
#print axioms SCD.Diagonal.offdiag_vanishes_of_static
#print axioms SCD.Diagonal.transverse_empty_of_two
#print axioms SCD.Diagonal.offdiag_zero_in_two
#print axioms SCD.Diagonal.constraint_count
#print axioms SCD.Diagonal.constraints_match_functions

-- Schwarzschild.lean
#print axioms SCD.Schwarzschild.ricci_combination
#print axioms SCD.Schwarzschild.vacuum_log_derivative
#print axioms SCD.Schwarzschild.scale_sum_derivative_zero
#print axioms SCD.Schwarzschild.vacuum_iff_scale_sum_stationary
#print axioms SCD.Schwarzschild.area_element_stationary

-- RicciDiag.lean
#print axioms SCD.RicciDiag.ricciTT_eq
#print axioms SCD.RicciDiag.ricciRR_eq
#print axioms SCD.RicciDiag.gravity_chain
#print axioms SCD.RicciDiag.area_stationary_derived

-- Vacuum.lean
#print axioms SCD.Vacuum.const_of_deriv_zero_and_vanishing
#print axioms SCD.Vacuum.reciprocity_of_asymptotic_flatness
#print axioms SCD.Vacuum.scale_product_eq_one
#print axioms SCD.Vacuum.product_constant_without_flatness
#print axioms SCD.Vacuum.tr_area_element_constant

-- Reciprocity.lean
#print axioms SCD.Reciprocity.sum_is_constant
#print axioms SCD.Reciprocity.pair_is_constant
#print axioms SCD.Reciprocity.reciprocal_iff_one
#print axioms SCD.Reciprocity.vacuum_gives_constant_product
#print axioms SCD.Reciprocity.radial_is_temporal_energy

-- Chain.lean
#print axioms SCD.Chain.gamma_is_the_prediction
#print axioms SCD.Chain.factor_two_is_weight_zero
#print axioms SCD.Chain.solar_ratio_is_two
#print axioms SCD.Chain.reciprocity_to_deflection
#print axioms SCD.Chain.reciprocity_is_derived
#print axioms SCD.Chain.chain_summary
#print axioms SCD.Chain.two_independent_weight_zero_tests

-- Deflection.lean
#print axioms SCD.Deflection.iso_is_exactly_half
#print axioms SCD.Deflection.iso_ratio_half
#print axioms SCD.Deflection.missing_half
#print axioms SCD.Deflection.solarObs_value
#print axioms SCD.Deflection.solarIso_value
#print axioms SCD.Deflection.solar_ratio
#print axioms SCD.Deflection.iso_fails_by_far

-- PPN.lean
#print axioms SCD.PPN.gamma_zero_is_isotropic
#print axioms SCD.PPN.gamma_one_is_observed
#print axioms SCD.PPN.reciprocal_expansion
#print axioms SCD.PPN.gamma_eq_one_of_reciprocal
#print axioms SCD.PPN.gamma_eq_one_first_order
#print axioms SCD.PPN.deflection_reciprocal_eq_observed
#print axioms SCD.PPN.halves_equal
#print axioms SCD.PPN.solar_reciprocal_value
#print axioms SCD.PPN.gamma_prediction_is_sharp

-- Precession.lean
#print axioms SCD.Precession.coeff_reciprocal
#print axioms SCD.Precession.coeff_isotropic
#print axioms SCD.Precession.isotropic_is_third
#print axioms SCD.Precession.coeff_affine_in_gamma
#print axioms SCD.Precession.mercuryFactor_bounds
#print axioms SCD.Precession.mercury_value
#print axioms SCD.Precession.mercury_isotropic_value
#print axioms SCD.Precession.two_tests_different_factors

-- Nonlinearity.lean
#print axioms SCD.Nonlinearity.beta_from_gamma
#print axioms SCD.Nonlinearity.beta_eq_one
#print axioms SCD.Nonlinearity.deviation_halves
#print axioms SCD.Nonlinearity.flat_shortcut_gives_half
#print axioms SCD.Nonlinearity.shortcut_is_off_by_two
#print axioms SCD.Nonlinearity.relation_is_falsifiable
#print axioms SCD.Nonlinearity.scalar_tensor_violates
#print axioms SCD.Nonlinearity.gr_satisfies_the_relation
#print axioms SCD.Nonlinearity.precession_coefficient_derived
#print axioms SCD.Nonlinearity.summary

-- Covariance.lean
#print axioms SCD.Covariance.CosmicHistory.sig_eq
#print axioms SCD.Covariance.CosmicHistory.Chr_eq
#print axioms SCD.Covariance.CosmicHistory.Rm_eq
#print axioms SCD.Covariance.CosmicHistory.Ric_eq_of_drift
#print axioms SCD.Covariance.CosmicHistory.Defm_eq
#print axioms SCD.Covariance.CosmicHistory.field_equation_form_invariant
#print axioms SCD.Covariance.CosmicHistory.no_local_expansion

-- Singularity.lean
#print axioms SCD.Singularity.ScaleField.scale_ne_zero
#print axioms SCD.Singularity.ScaleField.energy_ne_zero
#print axioms SCD.Singularity.ScaleField.conformal_factor_isUnit
#print axioms SCD.Singularity.ScaleField.conformal_factor_invertible
#print axioms SCD.Singularity.curvature_indep_of_scale_value
#print axioms SCD.Singularity.curvature_zero_of_uniform_scale

-- Horizon.lean
#print axioms SCD.Horizon.gtt_ne_zero
#print axioms SCD.Horizon.reciprocal_never_degenerate
#print axioms SCD.Horizon.redshift_never_infinite
#print axioms SCD.Horizon.no_degeneracy_anywhere
#print axioms SCD.Horizon.null_cone_scale_independent
#print axioms SCD.Horizon.waves_travel_on_the_light_cone
#print axioms SCD.Horizon.no_energy_dependent_speed
#print axioms SCD.Horizon.two_polarizations
#print axioms SCD.Horizon.no_breathing_mode
#print axioms SCD.Horizon.polarization_count
#print axioms SCD.Horizon.entropy_of_scale_ratio
#print axioms SCD.Horizon.entropy_doubling_is_additive
#print axioms SCD.Horizon.entropy_increment_independent_of_size
#print axioms SCD.Horizon.no_minimum_length
#print axioms SCD.Horizon.no_final_description

-- Waves.lean
#print axioms SCD.Waves.conserved_has_no_dynamics
#print axioms SCD.Waves.monopole_does_not_radiate
#print axioms SCD.Waves.dipole_does_not_radiate
#print axioms SCD.Waves.quadrupole_is_leading
#print axioms SCD.Waves.drift_descends
#print axioms SCD.Waves.total_conserved
#print axioms SCD.Waves.localised_iff_proper
#print axioms SCD.Waves.power_pos
#print axioms SCD.Waves.power_ratio_halving
#print axioms SCD.Waves.inspiral_shrinks_orbit
#print axioms SCD.Waves.separation_rate
#print axioms SCD.Waves.chirpMass_symm
#print axioms SCD.Waves.chirpMass_equal
#print axioms SCD.Waves.chirp_exponent
#print axioms SCD.Waves.chirp_mass_exponent
#print axioms SCD.Waves.hulse_taylor_agreement
#print axioms SCD.Waves.dipole_bounded_by_hulse_taylor
#print axioms SCD.Waves.gw250114_radiated_fraction
#print axioms SCD.Waves.area_law_confirmed
#print axioms SCD.Waves.gw150914_equal_mass_component
#print axioms SCD.Waves.dipole_bounded_by_double_pulsar
#print axioms SCD.Waves.double_pulsar_tighter
#print axioms SCD.Waves.reflectivity_nonzero_but_unbounded
#print axioms SCD.Waves.echo_delay_logarithmic
#print axioms SCD.Waves.delay_insensitive_to_reflectivity
#print axioms SCD.Waves.echo_train_is_a_comb
#print axioms SCD.Waves.echo_amplitudes_geometric
#print axioms SCD.Waves.null_search_bounds_reflectivity
#print axioms SCD.Waves.damping_is_the_looser_constraint
#print axioms SCD.Waves.scale_ratio_never_decreases
#print axioms SCD.Waves.log_law_is_not_area_law
#print axioms SCD.Waves.gw241011_spin_is_rapid
#print axioms SCD.Waves.spin_bound_beats_echo_bound
#print axioms SCD.Waves.no_ultralight_scalar_available
#print axioms SCD.Waves.same_constant_both_sectors

-- Index.lean
#print axioms SCD.Index.A6'_from_index
#print axioms SCD.Index.kappa_at_four
#print axioms SCD.Index.poisson_from_index
#print axioms SCD.Index.newtonian_potential_from_index
#print axioms SCD.Index.orientation_is_one_bit
#print axioms SCD.Index.no_period_no_source
#print axioms SCD.Index.no_period_no_gravity
#print axioms SCD.Index.reciprocity_of_no_enclosed_winding
#print axioms SCD.Index.reciprocity_broken_by_winding
#print axioms SCD.Index.coupling_is_one_dimensionless_number
#print axioms SCD.Index.enclosed_charge_additive
#print axioms SCD.Index.neutral_region_is_vacuum
#print axioms SCD.Index.index_form_summary
#print axioms SCD.Index.lap_mod_divergences

-- Flux.lean
#print axioms SCD.Flux.flux_eq_winding
#print axioms SCD.Flux.flux_combine
#print axioms SCD.Flux.flux_vacuum
#print axioms SCD.Flux.flux_pair
#print axioms SCD.Flux.flux_quantised
#print axioms SCD.Flux.flux_zero_of_no_period
#print axioms SCD.Flux.flux_and_hedgehog_both_additive
#print axioms SCD.Flux.gap_is_the_codimension

/-! ## PART II.c — witnesses -/


-- Witness.lean
#print axioms SCD.Witness.shift_is_exact
#print axioms SCD.Witness.shift_nontrivial
#print axioms SCD.Witness.shift_commutes_with_derivation
#print axioms SCD.Witness.linearFlow_moves
#print axioms SCD.Witness.constMoment_conserved
#print axioms SCD.Witness.scaleField_comparisons_carry_no_curvature
#print axioms SCD.Witness.scaleField_scale_is_faithful
#print axioms SCD.Witness.scaleShift_is_witnessed

-- ExpPoly.lean
#print axioms SCD.ExpPolyModel.der_single
#print axioms SCD.ExpPolyModel.der_zero
#print axioms SCD.ExpPolyModel.der_add
#print axioms SCD.ExpPolyModel.der_single_mul_single
#print axioms SCD.ExpPolyModel.induction_single
#print axioms SCD.ExpPolyModel.der_mul
#print axioms SCD.ExpPolyModel.der_comm
#print axioms SCD.ExpPolyModel.emb_zero
#print axioms SCD.ExpPolyModel.emb_add
#print axioms SCD.ExpPolyModel.emb_one
#print axioms SCD.ExpPolyModel.der_emb
#print axioms SCD.ExpPolyModel.expUnit_val
#print axioms SCD.ExpPolyModel.expUnit_add
#print axioms SCD.ExpPolyModel.der_expUnit
#print axioms SCD.ExpPolyModel.scaleField_sigma
#print axioms SCD.ExpPolyModel.scaleField_gradient_ne_zero
#print axioms SCD.ExpPolyModel.expUnit_zero
#print axioms SCD.ExpPolyModel.dirScale_s
#print axioms SCD.ExpPolyModel.reciprocal_of_neg
#print axioms SCD.ExpPolyModel.recipTwo_reciprocal
#print axioms SCD.ExpPolyModel.recipTwo_not_isotropic
#print axioms SCD.ExpPolyModel.exp_not_first_order

-- Circle.lean
#print axioms SCD.Circle.dloop_single
#print axioms SCD.Circle.dloop_zero
#print axioms SCD.Circle.dloop_add
#print axioms SCD.Circle.induction_single
#print axioms SCD.Circle.dloop_mul
#print axioms SCD.Circle.dloop_uPow
#print axioms SCD.Circle.dloop_coeff_zero
#print axioms SCD.Circle.no_potential
#print axioms SCD.Circle.no_scaleField_with_uPow
#print axioms SCD.Circle.ScaleGradient.ofScaleField_isExact
#print axioms SCD.Circle.circGradient_not_isExact
#print axioms SCD.Circle.toDefect_winding
#print axioms SCD.Circle.circGradient_isExact_iff
#print axioms SCD.Circle.toDefect_isTrivial_iff
#print axioms SCD.Circle.exact_iff_trivial

-- Gradient.lean
#print axioms SCD.Gradient.hess_congr
#print axioms SCD.Gradient.gradsq_congr
#print axioms SCD.Gradient.lap_congr
#print axioms SCD.Gradient.Chr_congr
#print axioms SCD.Gradient.Defm_congr
#print axioms SCD.Gradient.Rm_congr
#print axioms SCD.Gradient.Ric_congr
#print axioms SCD.Gradient.geometry_congr
#print axioms SCD.Gradient.fiducial_changes_no_geometry
#print axioms SCD.Gradient.exact_isClosed
#print axioms SCD.Gradient.closed_not_exact
#print axioms SCD.Gradient.logDeriv_spec
#print axioms SCD.Gradient.grad_unique
#print axioms SCD.Gradient.grad_eq_logDeriv
#print axioms SCD.Gradient.d_inv
#print axioms SCD.Gradient.logDeriv_closed

-- Torus.lean
#print axioms SCD.Torus.dtor_single
#print axioms SCD.Torus.dtor_zero
#print axioms SCD.Torus.dtor_add
#print axioms SCD.Torus.induction_single
#print axioms SCD.Torus.dtor_mul
#print axioms SCD.Torus.dtor_comm
#print axioms SCD.Torus.dtor_uTor
#print axioms SCD.Torus.dtor_coeff_zero
#print axioms SCD.Torus.no_potential_tor
#print axioms SCD.Torus.torGradient_not_isExact
#print axioms SCD.Torus.twoTorus_not_isExact

-- Amendment.lean
#print axioms SCD.Amendment.sig_eq_logDeriv
#print axioms SCD.Amendment.same_unit_same_geometry
#print axioms SCD.Amendment.ofUnitOfPotential_s
#print axioms SCD.Amendment.potential_unique_up_to_fiducial
#print axioms SCD.Amendment.what_A2_adds

/-! ## PART II.b — the anisotropic sector -/


-- Gauge.lean
#print axioms SCD.Gauge.mem_stabilizer_iff
#print axioms SCD.Gauge.stabilizer_eq_bot_of_injective
#print axioms SCD.Gauge.stabilizer_eq_top_of_isotropic
#print axioms SCD.Gauge.sameOrbit_iff_eq_scale
#print axioms SCD.Gauge.internal_symmetry_determined

-- Transport.lean
#print axioms SCD.Transport.transports_self_iff
#print axioms SCD.Transport.transport_unique_of_nondegenerate
#print axioms SCD.Transport.transport_coset
#print axioms SCD.Transport.transports_of_stabilizer
#print axioms SCD.Transport.transport_unique_iff_stabilizer_trivial
#print axioms SCD.Transport.nondegenerate_no_gauge_freedom

-- Axis.lean
#print axioms SCD.Axis.bareForm_neg
#print axioms SCD.Axis.physForm_neg
#print axioms SCD.Axis.neg_indistinguishable
#print axioms SCD.Axis.physForm_indistinguishable
#print axioms SCD.Axis.isotropic_no_order_parameter
#print axioms SCD.Axis.nondegenerate_full_frame
#print axioms SCD.Axis.uniaxial_stabilizer
#print axioms SCD.Axis.uniaxial_axis_distinguished
#print axioms SCD.Axis.scalar_picture_is_the_isotropic_locus

-- Defect.lean
#print axioms SCD.Defect.ScaleDefect.winding_unique
#print axioms SCD.Defect.ScaleDefect.vacuum_winding
#print axioms SCD.Defect.ScaleDefect.combine_winding
#print axioms SCD.Defect.ScaleDefect.anti_winding
#print axioms SCD.Defect.ScaleDefect.pair_winding_zero
#print axioms SCD.Defect.ScaleDefect.vacuum_isTrivial
#print axioms SCD.Defect.ScaleDefect.stable_of_winding_ne_zero
#print axioms SCD.Defect.ScaleDefect.winding_eq_zero_of_trivial
#print axioms SCD.Defect.ScaleDefect.toCharge_block
#print axioms SCD.Defect.ScaleDefect.toCharge_hedgehog
#print axioms SCD.Defect.ScaleDefect.toCharge_combine
#print axioms SCD.Defect.ScaleDefect.toCharge_anti
#print axioms SCD.Defect.ScaleDefect.toCharge_vacuum
#print axioms SCD.Defect.ScaleDefect.toCharge_observable
#print axioms SCD.Defect.ScaleDefect.mass_pos
#print axioms SCD.Defect.ScaleDefect.antiparticle_same_mass
#print axioms SCD.Defect.ScaleDefect.mass_zero
#print axioms SCD.Defect.ScaleDefect.mass_ratio_geometric
#print axioms SCD.Defect.ScaleDefect.mass_ratio_const

-- Charges.lean
#print axioms SCD.Charges.DefectCharge.comp_block
#print axioms SCD.Charges.DefectCharge.comp_hedgehog
#print axioms SCD.Charges.DefectCharge.anti_block
#print axioms SCD.Charges.DefectCharge.anti_hedgehog
#print axioms SCD.Charges.DefectCharge.triv_observable
#print axioms SCD.Charges.DefectCharge.block_confined
#print axioms SCD.Charges.DefectCharge.hedgehog_free
#print axioms SCD.Charges.DefectCharge.hedgehog_surjective_on_observables
#print axioms SCD.Charges.DefectCharge.exactly_one_confined
#print axioms SCD.Charges.DefectCharge.hedgehog_not_determined_by_block
#print axioms SCD.Charges.DefectCharge.block_not_determined_by_hedgehog
#print axioms SCD.Charges.DefectCharge.charges_independent
#print axioms SCD.Charges.DefectCharge.pair_observable
#print axioms SCD.Charges.DefectCharge.pair_hedgehog_zero
#print axioms SCD.Charges.DefectCharge.observable_pair_any_hedgehog

-- Particle.lean
#print axioms SCD.Particle.boost_injective
#print axioms SCD.Particle.pattern_is_one_vector
#print axioms SCD.Particle.mixture_second_moment
#print axioms SCD.Particle.mixture_cvSq_ge_one
#print axioms SCD.Particle.mixture_cvSq_eq_one_iff
#print axioms SCD.Particle.observed_disfavours_higher_rank
#print axioms SCD.Particle.rate_value_not_fixed
#print axioms SCD.Particle.block_two_valued
#print axioms SCD.Particle.block_cannot_be_three_valued
#print axioms SCD.Particle.block_self_inverse
#print axioms SCD.Particle.bind_hedgehog
#print axioms SCD.Particle.bind_block
#print axioms SCD.Particle.two_odd_make_even
#print axioms SCD.Particle.hedgehog_conserved_in_splitting
#print axioms SCD.Particle.no_further_label
#print axioms SCD.Particle.particle_label_structure

-- Emergence.lean
#print axioms SCD.Emergence.mem_resolved
#print axioms SCD.Emergence.resolved_mono
#print axioms SCD.Emergence.content_never_complete
#print axioms SCD.Emergence.always_more_above
#print axioms SCD.Emergence.no_fundamental_list
#print axioms SCD.Emergence.mass_iff_threshold
#print axioms SCD.Emergence.mass_mono
#print axioms SCD.Emergence.content_eq_of_no_threshold
#print axioms SCD.Emergence.content_changes_only_at_threshold

/-! ## PART III — the quantum sector -/


-- Deformation.lean
#print axioms SCD.Deformation.Biderivation.poisson_antisymm
#print axioms SCD.Deformation.Biderivation.poisson_self
#print axioms SCD.Deformation.Biderivation.poisson_leibniz_left
#print axioms SCD.Deformation.Biderivation.poisson_leibniz_right
#print axioms SCD.Deformation.Biderivation.generator_conserves_self
#print axioms SCD.Deformation.Biderivation.energy_cannot_generate_own_drift
#print axioms SCD.Deformation.star_assoc
#print axioms SCD.Deformation.star_classical
#print axioms SCD.Deformation.star_comm_classical
#print axioms SCD.Deformation.star_commutator
#print axioms SCD.Deformation.star_comm_iff_poisson_zero
#print axioms SCD.Deformation.star_commutator_embed
#print axioms SCD.Deformation.canonical_poisson
#print axioms SCD.Deformation.ccr_of_canonical
#print axioms SCD.Deformation.ccr_of_canonical_star
#print axioms SCD.Deformation.canonical_poisson_self
#print axioms SCD.Deformation.energy_generates_conserved_drift
#print axioms SCD.Deformation.energy_generates_conserved_drift_star

-- Crossed.lean
#print axioms SCD.Crossed.ScaleShift.map_zero
#print axioms SCD.Crossed.ScaleShift.shiftOp_apply
#print axioms SCD.Crossed.mulOp_apply
#print axioms SCD.Crossed.shift_mul_eq
#print axioms SCD.Crossed.commutator_eq
#print axioms SCD.Crossed.comm_iff_shift_trivial
#print axioms SCD.Crossed.delta_twisted_leibniz
#print axioms SCD.Crossed.delta_leibniz_of_untwisted
#print axioms SCD.Crossed.delta_eq_zero_iff
#print axioms SCD.Crossed.ScaleShift
#print axioms SCD.Crossed.shift_mul_eq_comp

-- Dual.lean
#print axioms SCD.Dual.R_branch_has_no_holonomy
#print axioms SCD.Dual.R_branch_is_trivial
#print axioms SCD.Dual.T_branch_has_holonomy
#print axioms SCD.Dual.gravity_selects_T_branch
#print axioms SCD.Dual.monodromy_shifts_the_unit
#print axioms SCD.Dual.monodromy_additive
#print axioms SCD.Dual.monodromy_trivial_iff_no_period
#print axioms SCD.Dual.fibre_is_a_torsor
#print axioms SCD.Dual.fibre_injective
#print axioms SCD.Dual.fibre_no_fixed_origin
#print axioms SCD.Dual.W3_summary

-- NCConformal.lean
#print axioms SCD.NCConformal.F_scaleConn
#print axioms SCD.NCConformal.F_scaleConn_eq_zero_iff
#print axioms SCD.NCConformal.Defm_antisymm_part
#print axioms SCD.NCConformal.Defm_symm_iff_commutator
#print axioms SCD.NCConformal.Defm_symm_iff_commute
#print axioms SCD.NCConformal.symmetric_part_uncorrected
#print axioms SCD.NCConformal.correction_is_pure_antisymmetric
#print axioms SCD.NCConformal.sum_Chr_Chr_full_nc
#print axioms SCD.NCConformal.sum_Chr_Chr_full_classical
#print axioms SCD.NCConformal.RmCorr_eq_zero_of_commute
#print axioms SCD.NCConformal.RmCorr_antisymm
#print axioms SCD.NCConformal.two_Rm_eq_nc
#print axioms SCD.NCConformal.two_Rm_eq_classical
#print axioms SCD.NCConformal.Rm_eq_zero_of_Defm_eq_zero_nc
#print axioms SCD.NCConformal.quantum_correction_is_a_wedge
#print axioms SCD.NCConformal.quantum_correction_couples_to_rotation
#print axioms SCD.NCConformal.correction_vanishes_on_commuting
#print axioms SCD.NCConformal.classical_iff_parallel
#print axioms SCD.NCConformal.RmCorr_eq_zero_of_parallel

-- Anisotropic.lean
#print axioms SCD.Anisotropic.DirField.anis_self
#print axioms SCD.Anisotropic.DirField.anis_antisymm
#print axioms SCD.Anisotropic.DirField.ofScalar_lg
#print axioms SCD.Anisotropic.DirField.ofScalar_s
#print axioms SCD.Anisotropic.DirField.ofScalar_anis
#print axioms SCD.Anisotropic.DirField.ofScalar_isotropic
#print axioms SCD.Anisotropic.DirField.grad_ofScalar
#print axioms SCD.Anisotropic.ChrDir_symm
#print axioms SCD.Anisotropic.ChrDir_of_isotropic
#print axioms SCD.Anisotropic.ChrDir_sub_Chr
#print axioms SCD.Anisotropic.ChrDir_correction_zero_of_eq
#print axioms SCD.Anisotropic.correction_is_optical_anisotropy
#print axioms SCD.Anisotropic.spatial_anisotropy_is_what_is_bounded
#print axioms SCD.Anisotropic.dirCommutator_self
#print axioms SCD.Anisotropic.dirCommutator_antisymm
#print axioms SCD.Anisotropic.dirCommutator_isotropic
#print axioms SCD.Anisotropic.dirCommutator_is_wedge
#print axioms SCD.Anisotropic.dirCommutator_is_leading

-- NCSize.lean
#print axioms SCD.NCSize.dir_commutator_star
#print axioms SCD.NCSize.iso_commutator_star
#print axioms SCD.NCSize.collinear_gradients_kill_it
#print axioms SCD.NCSize.spherical_static_gives_zero
#print axioms SCD.NCSize.noncollinear_witness
#print axioms SCD.NCSize.correction_is_not_identically_zero
#print axioms SCD.NCSize.leading_claim_has_no_failing_instance
#print axioms SCD.NCSize.summary

/-! ## PART IV — scale flow and content -/


-- RG.lean
#print axioms SCD.RG.ScaleFlow.observable_const_at_fixedPoint
#print axioms SCD.RG.ScaleFlow.fixedPoint_invariant
#print axioms SCD.RG.callan_symanzik
#print axioms SCD.RG.scale_invariant_of_fixedPoint
#print axioms SCD.RG.mem_active
#print axioms SCD.RG.active_mono
#print axioms SCD.RG.active_eq_of_no_threshold
#print axioms SCD.RG.active_finite_range
#print axioms SCD.RG.active_eq_univ_of_ge
#print axioms SCD.RG.active_eq_empty_of_lt
#print axioms SCD.RG.beta_const_between_thresholds
#print axioms SCD.RG.beta_finite_range
#print axioms SCD.RG.beta_eq_of_all_active

-- Running.lean
#print axioms SCD.Running.resolvedCount_self
#print axioms SCD.Running.invSqCoupling_at_base
#print axioms SCD.Running.hasDerivAt_invSqCoupling
#print axioms SCD.Running.slope_eq_two_b
#print axioms SCD.Running.invSqCoupling_eq_one_loop
#print axioms SCD.Running.asympt_free_iff_pos_density

-- QCD.lean
#print axioms SCD.QCD.running_inv_sq
#print axioms SCD.QCD.asymptotic_freedom
#print axioms SCD.QCD.lambda_invariant
#print axioms SCD.QCD.lambda_pos
#print axioms SCD.QCD.hadron_mass_ratio
#print axioms SCD.QCD.spectrum_rigid
#print axioms SCD.QCD.geometric_tower_fails
#print axioms SCD.QCD.ratio₁_value
#print axioms SCD.QCD.ratio₂_value
#print axioms SCD.QCD.lightestGlueballInLambda_value

-- Spectrum.lean
#print axioms SCD.Spectrum.mass_threshold_inverse
#print axioms SCD.Spectrum.equal_gaps_variance_zero
#print axioms SCD.Spectrum.observed_cvSq_value
#print axioms SCD.Spectrum.meanGap_value
#print axioms SCD.Spectrum.observed_not_geometric
#print axioms SCD.Spectrum.observed_within_scale_invariant_range
#print axioms SCD.Spectrum.densityFromGaps_value
#print axioms SCD.Spectrum.deltaN_inverse
#print axioms SCD.Spectrum.density_gap_inverse

-- Period.lean
#print axioms SCD.Period.couplingTimesDensity_eq
#print axioms SCD.Period.lattice_gives_one
#print axioms SCD.Period.coupling_under_lattice
#print axioms SCD.Period.coupling_under_lattice_four
#print axioms SCD.Period.lattice_cvSq
#print axioms SCD.Period.lattice_excluded
#print axioms SCD.Period.lattice_excluded_by_a_wide_margin
#print axioms SCD.Period.geometric_tower_is_the_lattice
#print axioms SCD.Period.retraction_closed_the_route
#print axioms SCD.Period.root_normalisation_value
#print axioms SCD.Period.root_normalisation_at_three
#print axioms SCD.Period.candidates_disagree
#print axioms SCD.Period.no_prediction_of_the_coupling

-- Sources.lean
#print axioms SCD.Sources.lap_const_mul
#print axioms SCD.Sources.source_coefficient_scales
#print axioms SCD.Sources.coefficient_is_not_invariant
#print axioms SCD.Sources.couplings_scale_together
#print axioms SCD.Sources.coupling_ratio_invariant
#print axioms SCD.Sources.coupling_cross_product
#print axioms SCD.Sources.both_additive
#print axioms SCD.Sources.threshold_independent_of_charge

-- Weight.lean
#print axioms SCD.Weight.resolvedCount_invariant
#print axioms SCD.Weight.invSqCoupling_invariant
#print axioms SCD.Weight.source_coefficient_weight_one
#print axioms SCD.Weight.ratio_not_invariant
#print axioms SCD.Weight.only_gravity_crosses_the_weight
#print axioms SCD.Weight.product_invariant
#print axioms SCD.Weight.invariant_but_not_predicted
#print axioms SCD.Weight.cvSq_weight_zero
#print axioms SCD.Weight.wedge_ratio_weight_zero

-- Entropy.lean
#print axioms SCD.Entropy.mem_sat
#print axioms SCD.Entropy.subset_sat
#print axioms SCD.Entropy.card_le_card_sat
#print axioms SCD.Entropy.card_image_perm
#print axioms SCD.Entropy.entropy_nondecreasing
#print axioms SCD.Entropy.no_reverse_law
#print axioms SCD.Entropy.evolve_no_reverse_law
#print axioms SCD.Entropy.charge_change_implies_nonequilibrium
#print axioms SCD.Entropy.entropy_production_implies_nonequilibrium

-- Light.lean
#print axioms SCD.Light.unit_sq_mul_eq_zero_iff
#print axioms SCD.Light.isNull_iff_bare
#print axioms SCD.Light.isNull_scale_invariant
#print axioms SCD.Light.scale_determined_of_nonnull
#print axioms SCD.Light.physForm_ne_bareForm
#print axioms SCD.Light.null_weight_zero
#print axioms SCD.Light.physFormDir_of_isotropic
#print axioms SCD.Light.isNullDir_iff_bare_of_isotropic
#print axioms SCD.Light.twoScale_not_isotropic
#print axioms SCD.Light.bare_null_not_phys_null
#print axioms SCD.Light.phys_null_not_bare_null
#print axioms SCD.Light.light_blind_iff_isotropic_locus
#print axioms SCD.Light.null_plane_condition
#print axioms SCD.Light.speed_ratio_is_scale_ratio
#print axioms SCD.Light.no_birefringence_of_isotropic
#print axioms SCD.Light.physFormDir_eq_bareForm_rescaled
#print axioms SCD.Light.isNullDir_iff_bare_rescaled
#print axioms SCD.Light.michelson_morley_null
#print axioms SCD.Light.one_cone_for_every_sector
#print axioms SCD.Light.only_the_wedge_survives_rescaling

-- Observation.lean
#print axioms SCD.Observation.null_has_energy
#print axioms SCD.Observation.redshift_is_scale_ratio
#print axioms SCD.Observation.scale_differs_of_energy_differs
#print axioms SCD.Observation.obsEnergy_rescale
#print axioms SCD.Observation.redshift_fiducial_invariant
#print axioms SCD.Observation.causal_structure_still_blind
#print axioms SCD.Observation.obsEnergyDir_of_isotropic
#print axioms SCD.Observation.obsEnergyDir_eq_en_weighted
#print axioms SCD.Observation.redshift_dir_is_scale_ratio

-- Particles.lean
#print axioms SCD.Particles.energy_pos
#print axioms SCD.Particles.energy_ge
#print axioms SCD.Particles.one_le_scaleRatio
#print axioms SCD.Particles.scaleRatio_mono
#print axioms SCD.Particles.lifetime_ge
#print axioms SCD.Particles.lifetime_mono
#print axioms SCD.Particles.lifetime_at_rest
#print axioms SCD.Particles.available_mono
#print axioms SCD.Particles.not_available_of_lt

-- DarkMatter.lean
#print axioms SCD.Dark.detResp_pos
#print axioms SCD.Dark.detection_failure
#print axioms SCD.Dark.dark_matter_exists
#print axioms SCD.Dark.response_vanishes

-- DarkEnergy.lean
#print axioms SCD.Cosmology.hasDerivAt_exp_mul
#print axioms SCD.Cosmology.dissipation_solution
#print axioms SCD.Cosmology.energy_strictly_decreasing
#print axioms SCD.Cosmology.scaleFactor_eq
#print axioms SCD.Cosmology.hasDerivAt_scaleFactor
#print axioms SCD.Cosmology.hasDerivAt_hubble
#print axioms SCD.Cosmology.acceleration_pos
#print axioms SCD.Cosmology.open_universe_accelerates

-- Positivity.lean
#print axioms SCD.Positivity.sig_zero
#print axioms SCD.Positivity.sig_succ
#print axioms SCD.Positivity.gradsq_eq
#print axioms SCD.Positivity.hess_zero_zero
#print axioms SCD.Positivity.hess_off
#print axioms SCD.Positivity.nullDir_is_null
#print axioms SCD.Positivity.nullContract_eq
#print axioms SCD.Positivity.nullContract_pos
#print axioms SCD.Positivity.nullContract_neg
#print axioms SCD.Positivity.no_null_energy_condition
#print axioms SCD.Positivity.scale_small_but_nonzero
#print axioms SCD.Positivity.scale_large

-- Well.lean
#print axioms SCD.Well.stretch_ne_zero
#print axioms SCD.Well.no_positive_floor
#print axioms SCD.Well.no_ceiling
#print axioms SCD.Well.light_measured_speed_one
#print axioms SCD.Well.bare_crossing_sq
#print axioms SCD.Well.reciprocal_crossing_eq_length_sq
#print axioms SCD.Well.shapiro_delay_of_stretched
#print axioms SCD.Well.shapiro_advance_of_compressed
#print axioms SCD.Well.branch_trichotomy
#print axioms SCD.Well.depth_from_crossing_and_length
#print axioms SCD.Well.crossing_length_relation_has_no_parameter

-- Momentum.lean
#print axioms SCD.Momentum.dual_of_lower
#print axioms SCD.Momentum.dualForm_of_isotropic
#print axioms SCD.Momentum.dispersion_relation
#print axioms SCD.Momentum.massless_iff_null
#print axioms SCD.Momentum.massless_dispersion
#print axioms SCD.Momentum.mass_shell_at_threshold
#print axioms SCD.Momentum.same_shell_iff_same_threshold
#print axioms SCD.Momentum.sig_eq_ad_momentum
#print axioms SCD.Momentum.commutator_of_gradients
#print axioms SCD.Momentum.correction_vanishes_of_central
#print axioms SCD.Momentum.angular_charge_is_wedge

-- Openness.lean
#print axioms SCD.Openness.open_iff_not_mem
#print axioms SCD.Openness.open_iff_some_drift
#print axioms SCD.Openness.fiducial_no_drift
#print axioms SCD.Openness.fiducial_hess
#print axioms SCD.Openness.fiducial_lap
#print axioms SCD.Openness.fiducial_gradsq
#print axioms SCD.Openness.fiducial_Defm_eq_zero
#print axioms SCD.Openness.fiducial_flat
#print axioms SCD.Openness.closed_universe_is_empty
#print axioms SCD.Openness.open_of_deformation
#print axioms SCD.Openness.no_dissipation_in_one_direction
#print axioms SCD.Openness.openness_forbids_continuity_in_one_direction
#print axioms SCD.Openness.A5_A6_dichotomy

/-! ## PART V — predictions and data -/


-- Predictions.lean
#print axioms SCD.Predictions.accel_numerator
#print axioms SCD.Predictions.powerlaw_accel_numerator
#print axioms SCD.Predictions.accelerates_iff
#print axioms SCD.Predictions.eos_dissipationExponent
#print axioms SCD.Predictions.dissipationExponent_eos
#print axioms SCD.Predictions.eos_one
#print axioms SCD.Predictions.eos_eq_neg_one_iff
#print axioms SCD.Predictions.eos_lt_third_iff
#print axioms SCD.Predictions.eos_lt_neg_one_iff
#print axioms SCD.Predictions.worked_inversion
#print axioms SCD.Predictions.muon_lifetime_value
#print axioms SCD.Predictions.muon_matches_experiment
#print axioms SCD.Predictions.poundRebka_value
#print axioms SCD.Predictions.darkEnergyDensity_value
#print axioms SCD.Predictions.logScale_step
#print axioms SCD.Predictions.logScale_ratio_const
#print axioms SCD.Predictions.logScale_closed

-- Cosmos.lean
#print axioms SCD.Cosmos.shift_invariant_is_constant
#print axioms SCD.Cosmos.rate_constant_of_fiducial_invariance
#print axioms SCD.Cosmos.w_does_not_evolve
#print axioms SCD.Cosmos.scale_ratio_depends_only_on_difference
#print axioms SCD.Cosmos.no_first_moment
#print axioms SCD.Cosmos.finite_lookback_no_origin
#print axioms SCD.Cosmos.isotropic_gravitates_without_labels
#print axioms SCD.Cosmos.dark_matter_has_no_species
#print axioms SCD.Cosmos.two_dark_routes_differ
#print axioms SCD.Cosmos.resolvable_needs_width_below_gap
#print axioms SCD.Cosmos.mean_gap_bound
#print axioms SCD.Cosmos.broad_structures_unresolvable
#print axioms SCD.Cosmos.resolvability_boundary

-- Scanning.lean
#print axioms SCD.Scanning.two_scale_invariance_forces_difference
#print axioms SCD.Scanning.rate_may_vary
#print axioms SCD.Scanning.one_scale_recovers_constant
#print axioms SCD.Scanning.rate_from_threshold_spacing
#print axioms SCD.Scanning.scanRate_constant_iff
#print axioms SCD.Scanning.w_evolution_tracks_density
#print axioms SCD.Scanning.two_anomalies_one_number
#print axioms SCD.Scanning.anomalies_vanish_together
#print axioms SCD.Scanning.scan_never_completes
#print axioms SCD.Scanning.finite_history_no_origin

-- Response.lean
#print axioms SCD.Response.rate_is_kappa_rho
#print axioms SCD.Response.average_rate_is_scanRate
#print axioms SCD.Response.factorisation_is_falsifiable
#print axioms SCD.Response.spacingRatio_weight_zero
#print axioms SCD.Response.spacingRatio_fiducial_invariant
#print axioms SCD.Response.spacingRatio_not_constant
#print axioms SCD.Response.weight_zero_does_not_force_constancy
#print axioms SCD.Response.two_anomalies_holds_for_every_density
#print axioms SCD.Response.summary

-- Attraction.lean
#print axioms SCD.Attraction.signed_source_would_antigravitate
#print axioms SCD.Attraction.mass_is_orientation_free
#print axioms SCD.Attraction.source_is_nonneg
#print axioms SCD.Attraction.attraction_from_counting
#print axioms SCD.Attraction.universality_from_counting
#print axioms SCD.Attraction.both_signs_permitted
#print axioms SCD.Attraction.two_labels_two_behaviours
#print axioms SCD.Attraction.void_is_the_advance_branch
#print axioms SCD.Attraction.overdensity_is_the_delay_branch
#print axioms SCD.Attraction.counting_bound
#print axioms SCD.Attraction.advance_bounded_by_emptiness
#print axioms SCD.Attraction.traversability_summary

-- Native.lean
#print axioms SCD.Native.not_two_places_of_parallel
#print axioms SCD.Native.separation_is_oriented
#print axioms SCD.Native.single_anisotropy_boundary
#print axioms SCD.Native.label_forces_anisotropy
#print axioms SCD.Native.zero_window_resolves_nothing
#print axioms SCD.Native.content_is_interval_valued
#print axioms SCD.Native.no_global_field_equation
#print axioms SCD.Native.ordering_discrepancy_is_the_observable
#print axioms SCD.Native.parity_conserved_under_binding
#print axioms SCD.Native.both_labels_conserved
#print axioms SCD.Native.entropy_order_is_scale_order
#print axioms SCD.Native.entropy_strict_iff_scale_strict
#print axioms SCD.Native.arrows_are_one_order
#print axioms SCD.Native.no_maximum_anisotropy
#print axioms SCD.Native.no_cutoff_either_end

-- Data.lean
#print axioms SCD.Data.desi_tension_exceeds_three_sigma
#print axioms SCD.Data.desi_significance_dataset_dependent
#print axioms SCD.Data.desi_combinations_disagree_internally
#print axioms SCD.Data.falsification_threshold
#print axioms SCD.Data.ccl_above_bound
#print axioms SCD.Data.gkpy_below_bound
#print axioms SCD.Data.determinations_straddle_bound
#print axioms SCD.Data.gkpy_updated_inside
#print axioms SCD.Data.kappa_below_bound
#print axioms SCD.Data.rho_below_bound
#print axioms SCD.Data.delta_below_bound
#print axioms SCD.Data.z_boson_far_inside
#print axioms SCD.Data.bound_separates_kappa_from_sigma
#print axioms SCD.Data.breit_wigner_spans_the_bound
#print axioms SCD.Data.dispersion_limit_above_planck
#print axioms SCD.Data.framework_predicts_no_finite_scale
#print axioms SCD.Data.one_charge_prediction
#print axioms SCD.Data.zero_nu_beta_beta_decides
#print axioms SCD.Data.probed_range_orders
#print axioms SCD.Data.no_second_switch_observed
#print axioms SCD.Data.breakings_are_refinements
#print axioms SCD.Data.electroweak_strictly_refines
#print axioms SCD.Data.scorecard

/-! ## PART VI — the register -/


-- Color.lean
#print axioms SCD.Color.BlockMonodromy.comp_perm
#print axioms SCD.Color.BlockMonodromy.anti_perm
#print axioms SCD.Color.BlockMonodromy.triv_perm
#print axioms SCD.Color.BlockMonodromy.charge_comp
#print axioms SCD.Color.BlockMonodromy.charge_anti
#print axioms SCD.Color.BlockMonodromy.triv_observable
#print axioms SCD.Color.BlockMonodromy.confinement
#print axioms SCD.Color.BlockMonodromy.pair_observable
#print axioms SCD.Color.BlockMonodromy.pair_charge
#print axioms SCD.Color.BlockMonodromy.rep_perm
#print axioms SCD.Color.BlockMonodromy.rep_charge
#print axioms SCD.Color.BlockMonodromy.bound_state_observable
#print axioms SCD.Color.BlockMonodromy.bound_state_size
#print axioms SCD.Color.BlockMonodromy.no_partial_state
#print axioms SCD.Color.BlockMonodromy.constituent_charge_fraction
#print axioms SCD.Color.BlockMonodromy.constituent_charge_rat
#print axioms SCD.Color.BlockMonodromy.bound_charge_divisible
#print axioms SCD.Color.BlockMonodromy.toCharge_block
#print axioms SCD.Color.BlockMonodromy.toCharge_hedgehog
#print axioms SCD.Color.BlockMonodromy.toCharge_comp
#print axioms SCD.Color.BlockMonodromy.toCharge_anti
#print axioms SCD.Color.BlockMonodromy.toCharge_triv
#print axioms SCD.Color.BlockMonodromy.observable_iff_toCharge_observable

-- ColorAudit.lean
#print axioms SCD.ColorAudit.identification_predicts_two
#print axioms SCD.ColorAudit.identification_predicts_halves
#print axioms SCD.ColorAudit.identification_fails_baryon
#print axioms SCD.ColorAudit.identification_fails_charge
#print axioms SCD.ColorAudit.spatial_block_is_not_colour_block
#print axioms SCD.ColorAudit.three_is_forced_by_data
#print axioms SCD.ColorAudit.three_matches_charge
#print axioms SCD.ColorAudit.geometry_offers_two_data_needs_three

-- Codimension.lean
#print axioms SCD.Codimension.defectDim_two
#print axioms SCD.Codimension.defectDim_three
#print axioms SCD.Codimension.defectDim_four
#print axioms SCD.Codimension.pointlike_iff_two_dim
#print axioms SCD.Codimension.three_dim_gives_strings
#print axioms SCD.Codimension.pointlike_forces_three
#print axioms SCD.Codimension.our_world_gives_strings
#print axioms SCD.Codimension.no_pointlike_in_four
#print axioms SCD.Codimension.string_mass_not_topological
#print axioms SCD.Codimension.stringMass_strictMono
#print axioms SCD.Codimension.stringMass_zero
#print axioms SCD.Codimension.extended_or_low_dimensional

-- Expressive.lean
#print axioms SCD.Expressive.diffPattern_shift
#print axioms SCD.Expressive.invariant_factors
#print axioms SCD.Expressive.diffPattern_invariant
#print axioms SCD.Expressive.invariant_iff_diffPattern
#print axioms SCD.Expressive.eval_not_invariant
#print axioms SCD.Expressive.scale_says_nothing_about_rotation
#print axioms SCD.Expressive.rotation_says_nothing_about_scale
#print axioms SCD.Expressive.channels_independent
#print axioms SCD.Expressive.neither_channel_complete
#print axioms SCD.Expressive.no_channel_coupling

-- CrossCheck.lean
#print axioms SCD.CrossCheck.rhoAll_value
#print axioms SCD.CrossCheck.rhoQuark_value
#print axioms SCD.CrossCheck.densities_differ
#print axioms SCD.CrossCheck.density_ratio_near_two
#print axioms SCD.CrossCheck.sector_relation_is_identity
#print axioms SCD.CrossCheck.qcd_extraction_returns_input
#print axioms SCD.CrossCheck.no_second_determination
#print axioms SCD.CrossCheck.quarkCvSq_value
#print axioms SCD.CrossCheck.quark_not_geometric

-- MassAudit.lean
#print axioms SCD.MassAudit.massExp_neg
#print axioms SCD.MassAudit.massQuad_neg
#print axioms SCD.MassAudit.massExp_pos
#print axioms SCD.MassAudit.massQuad_pos
#print axioms SCD.MassAudit.massExp_zero
#print axioms SCD.MassAudit.massQuad_zero
#print axioms SCD.MassAudit.mass_law_underdetermined
#print axioms SCD.MassAudit.both_laws_antiparticle_degenerate
#print axioms SCD.MassAudit.massQuad_ratio_not_constant

-- Audit.lean
#print axioms SCD.Audit.scalar_for_directional_count
#print axioms SCD.Audit.direction_for_position_count
#print axioms SCD.Audit.homotopy_class_count
#print axioms SCD.Audit.register_was_incomplete
#print axioms SCD.Audit.register_nonempty
#print axioms SCD.Audit.audit_found_more_than_it_closed
#print axioms SCD.Audit.more_corrected_than_retracted
#print axioms SCD.Audit.index_substitutions_still_occur
#print axioms SCD.Audit.unification_added_nothing
#print axioms SCD.Audit.register_grew_under_audit
#print axioms SCD.Audit.clean_count

end SCD.Verify
