/-
# The non-commutative foundation

The geometric sector of this development works over a *commutative* ring.  That
was a defensible choice for gravity — classical geometry is commutative — but
it cannot be the foundation, because quantum mechanics is not.  This file
supplies the correction, and the correction turns out to strengthen the
programme rather than patch it.

The observation is this.  The geometric sector never used commutativity to
*state* its differential axioms; it used a Leibniz rule and equality of mixed
partials.  Both of those hold verbatim for **inner derivations** `ad p = [p,·]`
in an arbitrary, possibly non-commutative ring.  So the differential structure
of the classical theory is not an extra postulate at all: it is what a
commutator does.

Concretely we prove:

* `ad p` obeys Leibniz in any ring (`ad_leibniz`);
* the failure of two such derivations to commute is itself an inner
  derivation — the Jacobi identity (`ad_jacobi`) — so they commute exactly when
  their generators commute up to something central;
* from the canonical commutation relation `[X,P] = c` alone, one derives
  `[P, Xⁿ⁺¹] = (n+1)Xⁿc`, i.e. **the power rule of differential calculus**
  (`ad_pow`).  Classical calculus is a theorem about commutators, not an
  independent assumption;
* the Robertson inequality, hence Heisenberg uncertainty
  `ΔX·ΔP ≥ ħ/2` (`heisenberg`).

The physical reading is the point.  Axiom A3 said `ε·s = 1`: energy scale times
length scale is one.  In a commutative algebra that identity is exact and one
gets classical geometry.  In a non-commutative algebra it *cannot* be exact,
and the obstruction is precisely `ħ`.  Gravity and quantum mechanics are then
the same duality read in the two available regimes — commuting and
non-commuting — rather than two theories to be reconciled.
-/
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Tactic.NoncommRing
import Mathlib.Tactic.LinearCombination

namespace ScaleUniverse.Quantum

/-! ## Inner derivations -/

section Ring

variable {A : Type*} [Ring A]

/-- The inner derivation generated by `p`, i.e. the commutator `[p, ·]`.

In the classical sector we *postulated* operators `∂ᵢ` obeying Leibniz and
commuting with one another.  Here they are not postulated: they are
commutators. -/
def ad (p a : A) : A := p * a - a * p

@[simp] theorem ad_zero (p : A) : ad p 0 = 0 := by simp [ad]

@[simp] theorem ad_zero_left (a : A) : ad 0 a = 0 := by simp [ad]

@[simp] theorem ad_self (p : A) : ad p p = 0 := by simp [ad]

theorem ad_add (p a b : A) : ad p (a + b) = ad p a + ad p b := by
  simp only [ad]; noncomm_ring

theorem ad_sub (p a b : A) : ad p (a - b) = ad p a - ad p b := by
  simp only [ad]; noncomm_ring

/-- **Leibniz rule, in any ring.**  This is the axiom `d_mul` of the classical
sector, holding here with no commutativity whatsoever. -/
theorem ad_leibniz (p a b : A) : ad p (a * b) = ad p a * b + a * ad p b := by
  simp only [ad]; noncomm_ring

/-- **Jacobi identity.**  The failure of two inner derivations to commute is
itself the inner derivation generated by the commutator of their generators. -/
theorem ad_jacobi (p q a : A) : ad p (ad q a) - ad q (ad p a) = ad (ad p q) a := by
  simp only [ad]; noncomm_ring

/-- **Equality of mixed partials, in any ring.**  This is the axiom `d_comm`
of the classical sector.  It holds exactly when the generators commute — which
is the precise sense in which a *coordinate system* is a choice of commuting
observables. -/
theorem ad_comm_of_commute {p q : A} (h : ad p q = 0) (a : A) :
    ad p (ad q a) = ad q (ad p a) := by
  have hj := ad_jacobi p q a
  rw [h, ad_zero_left] at hj
  exact sub_eq_zero.mp hj

/-! ## Canonical commutation relations give classical calculus

Assume only `[P, X] = c` with `c` central.  Nothing else. -/

/-- **The power rule, derived from the commutator.**

`[P, Xⁿ⁺¹] = (n+1) Xⁿ c`.

With `c = -iħ` and `∂ := (iħ)⁻¹ ad P`, this reads `∂(xⁿ⁺¹) = (n+1)xⁿ`: the
derivative of the classical sector *is* the commutator, and the power rule is a
theorem about non-commutativity rather than an axiom of analysis. -/
theorem ad_pow {P X c : A} (hc : ∀ y : A, c * y = y * c) (h : ad P X = c) :
    ∀ n : ℕ, ad P (X ^ (n + 1)) = ((n : A) + 1) * (X ^ n * c) := by
  intro n
  induction n with
  | zero => simpa using h
  | succ m ih =>
      have hstep : ad P (X ^ (m + 1 + 1)) = ad P X * X ^ (m + 1) + X * ad P (X ^ (m + 1)) := by
        rw [pow_succ' X (m + 1)]
        exact ad_leibniz P X (X ^ (m + 1))
      have hcomm : Commute ((m : A) + 1) X :=
        (Nat.cast_commute m X).add_left (Commute.one_left X)
      have hxc : X * (((m : A) + 1) * (X ^ m * c)) = ((m : A) + 1) * (X ^ (m + 1) * c) := by
        rw [← mul_assoc, ← hcomm.eq, mul_assoc, ← mul_assoc X (X ^ m) c, ← pow_succ' X m]
      rw [hstep, h, ih, hxc, hc (X ^ (m + 1))]
      push_cast
      noncomm_ring

end Ring

/-! ## The uncertainty principle

A3 (`ε·s = 1`) is an exact identity only in a commutative algebra.  Once the
algebra fails to commute, the duality can only hold up to the commutator — and
the quantitative form of that statement is the Robertson inequality. -/

section Uncertainty

variable {V : Type*} [NormedAddCommGroup V] [InnerProductSpace ℂ V]

local notation "⟪" x ", " y "⟫" => @inner ℂ _ _ x y

/-- **Robertson inequality.**

For symmetric operators `A`, `B` and a unit vector `ψ`,

  `‖⟪ψ, (AB − BA)ψ⟫‖ ≤ 2 ‖Aψ‖ ‖Bψ‖`.

The commutator of two observables bounds the product of their spreads.  This is
the whole content of the uncertainty principle; the constant `ħ/2` appears only
when the commutator is evaluated. -/
theorem robertson (A B : V →ₗ[ℂ] V)
    (hA : ∀ x y : V, ⟪A x, y⟫ = ⟪x, A y⟫)
    (hB : ∀ x y : V, ⟪B x, y⟫ = ⟪x, B y⟫)
    (ψ : V) :
    ‖⟪ψ, A (B ψ)⟫ - ⟪ψ, B (A ψ)⟫‖ ≤ 2 * (‖A ψ‖ * ‖B ψ‖) := by
  have h1 : ⟪ψ, A (B ψ)⟫ = ⟪A ψ, B ψ⟫ := (hA ψ (B ψ)).symm
  have h2 : ⟪ψ, B (A ψ)⟫ = ⟪B ψ, A ψ⟫ := (hB ψ (A ψ)).symm
  rw [h1, h2]
  have hconj : ⟪B ψ, A ψ⟫ = (starRingEnd ℂ) ⟪A ψ, B ψ⟫ := (inner_conj_symm _ _).symm
  rw [hconj]
  have hbound : ‖⟪A ψ, B ψ⟫ - (starRingEnd ℂ) ⟪A ψ, B ψ⟫‖ ≤ 2 * ‖⟪A ψ, B ψ⟫‖ := by
    calc ‖⟪A ψ, B ψ⟫ - (starRingEnd ℂ) ⟪A ψ, B ψ⟫‖
        ≤ ‖⟪A ψ, B ψ⟫‖ + ‖(starRingEnd ℂ) ⟪A ψ, B ψ⟫‖ := norm_sub_le _ _
      _ = 2 * ‖⟪A ψ, B ψ⟫‖ := by rw [RCLike.norm_conj]; ring
  refine hbound.trans ?_
  have hcs : ‖⟪A ψ, B ψ⟫‖ ≤ ‖A ψ‖ * ‖B ψ‖ := norm_inner_le_norm _ _
  linarith

/-- **Heisenberg uncertainty.**

If the commutator of two symmetric observables acts on `ψ` as the scalar `iħ`,
then their spreads satisfy `ħ ≤ 2‖Aψ‖‖Bψ‖`, i.e. `ΔA·ΔB ≥ ħ/2`.

`A` and `B` are understood as already centred on their expectation values, so
`‖Aψ‖` and `‖Bψ‖` are the standard deviations. -/
theorem heisenberg (A B : V →ₗ[ℂ] V)
    (hA : ∀ x y : V, ⟪A x, y⟫ = ⟪x, A y⟫)
    (hB : ∀ x y : V, ⟪B x, y⟫ = ⟪x, B y⟫)
    (ψ : V) (hψ : ‖ψ‖ = 1) (ħ : ℝ)
    (hccr : A (B ψ) - B (A ψ) = (Complex.I * (ħ : ℂ)) • ψ) :
    |ħ| ≤ 2 * (‖A ψ‖ * ‖B ψ‖) := by
  have hsplit : ⟪ψ, A (B ψ)⟫ - ⟪ψ, B (A ψ)⟫ = ⟪ψ, A (B ψ) - B (A ψ)⟫ := by
    rw [inner_sub_right]
  have hval : ⟪ψ, A (B ψ) - B (A ψ)⟫ = (Complex.I * (ħ : ℂ)) * ⟪ψ, ψ⟫ := by
    rw [hccr, inner_smul_right]
  have hnorm : ‖ψ‖ ^ 2 = 1 := by rw [hψ]; norm_num
  have hinner : ⟪ψ, ψ⟫ = (1 : ℂ) := by
    rw [inner_self_eq_norm_sq_to_K, hψ]
    norm_num
  have hfinal : ‖⟪ψ, A (B ψ)⟫ - ⟪ψ, B (A ψ)⟫‖ = |ħ| := by
    rw [hsplit, hval, hinner, mul_one, norm_mul, Complex.norm_I, one_mul,
      Complex.norm_real, Real.norm_eq_abs]
  rw [← hfinal]
  exact robertson A B hA hB ψ

end Uncertainty

end ScaleUniverse.Quantum
