#!/usr/bin/env python3
"""Keep Verify.lean, the report's file table, and the theorem index in step with
the sources — and fail loudly if anything has drifted.

Run from the repository root:

    python3 tools/sync_report.py            # check only, exits 1 on drift
    python3 tools/sync_report.py --write    # regenerate the generated blocks

What it enforces:
  * every theorem in SCD/*.lean appears in SCD/Verify.lean exactly once
  * every \\leanline{...} citation in the report names something that exists
  * the theorem counts quoted in the report match the sources
"""
import re, os, sys, io

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def _read(path):
    """UTF-8, newlines left alone: the sources are UTF-8 and LF, and Windows'
    default cp1252 + CRLF translation would fail on the first and rewrite every
    line of the second."""
    with io.open(path, encoding='utf-8', newline='') as f:
        return f.read()


def _write(path, text):
    with io.open(path, 'w', encoding='utf-8', newline='') as f:
        f.write(text)


SRC = os.path.join(ROOT, 'SCD')
TEX = os.path.join(ROOT, 'paper', 'SCD.tex')

# reading order, mirroring SCD.lean; (part title in English, part title in Chinese, modules)
PARTS = [
    ("PART 0 — the postulates", "第一部分\\quad 公理",
     ["Pattern", "Basic", "Axioms", "Postulates"]),
    ("PART I — what the axioms force", "第二部分\\quad 公理逼出什么",
     ["Foundation", "Signature", "Invariant", "Quantum", "Direction", "Connection",
      "Coupling", "Algebra", "Dimension", "Slice", "Axes"]),
    ("PART II — the branch point", "第三部分\\quad 分叉点",
     ["Locus", "Dynamics", "Determination", "Explanation", "Anchor", "Observer", "Observed", "Internal", "Triple", "Mutual", "Ordering", "Screen", "Resolution", "Layers", "Spacing", "Information", "Conversion", "Overdetermination", "RateWeight", "Bridge", "Observations", "Disconnect", "Content", "Size", "Valuation", "OneParameter", "Codimension2", "DegreeSource"]),
    ("PART II.a — the isotropic sector", "第四部分\\quad 各向同性扇区",
     ["Conformal", "Frame", "Unify", "Newton", "Diagonal", "Schwarzschild", "RicciDiag", "Vacuum", "Reciprocity", "Chain",
      "Deflection", "PPN", "Precession", "Nonlinearity", "Covariance", "Singularity", "Horizon", "Waves",
      "Index", "Flux"]),
    ("PART II.c — witnesses", "第四部分附\\quad 结构的见证",
     ["Witness", "ExpPoly", "Circle", "Gradient", "Torus", "Amendment"]),
    ("PART II.b — the anisotropic sector", "第五部分\\quad 各向异性扇区",
     ["Gauge", "Transport", "Axis", "Defect", "Charges", "Particle", "Emergence"]),
    ("PART III — the quantum sector", "第六部分\\quad 量子扇区",
     ["Deformation", "Crossed", "Dual", "NCConformal", "Anisotropic", "NCSize"]),
    ("PART IV — scale flow and content", "第七部分\\quad 标度流与内容",
     ["RG", "Running", "QCD", "Spectrum", "Period", "Sources", "Weight", "Entropy", "Light", "Observation",
      "Particles", "DarkMatter", "DarkEnergy", "Positivity", "Well", "Momentum", "Openness"]),
    ("PART V — predictions and data", "第八部分\\quad 预言与数据",
     ["Predictions", "Cosmos", "Scanning", "Response", "Attraction", "Native", "Data"]),
    ("PART VI — the register", "第九部分\\quad 登记册",
     ["Color", "ColorAudit", "Codimension", "Expressive", "CrossCheck", "MassAudit", "Audit"]),
]

DECL = r'^(?:@\[[^\]]*\]\s*)?(?:theorem|def|noncomputable def|abbrev|structure|class|instance)\s+([A-Za-z_][\w₀-₉\']*)'
THM = r'^(?:@\[[^\]]*\]\s*)?theorem\s+([A-Za-z_][\w₀-₉\']*)'


def strip_docs(s):
    return re.sub(r'/-(?!!).*?-/', '', s, flags=re.S)


def theorems(mod):
    """Theorem names in a module, in source order."""
    return re.findall(THM, strip_docs(_read(f'{SRC}/{mod}.lean')), re.M)


def qualified(mod):
    """Fully-qualified theorem names, tracking the namespace stack."""
    s = strip_docs(_read(f'{SRC}/{mod}.lean'))
    stack, out = [], []
    for line in s.split('\n'):
        m = re.match(r'\s*namespace\s+([A-Za-z_][\w.]*)', line)
        if m:
            stack.append(m.group(1)); continue
        m = re.match(r'\s*end\s+([A-Za-z_][\w.]*)\s*$', line)
        if m and stack and stack[-1].split('.')[-1] == m.group(1).split('.')[-1]:
            stack.pop(); continue
        m = re.match(r'\s*(?:@\[[^\]]*\]\s*)?theorem\s+([A-Za-z_][\w₀-₉\']*)', line)
        if m:
            out.append('.'.join(stack + [m.group(1)]))
    return out


def check_modules():
    listed = {m for _, _, ms in PARTS for m in ms}
    actual = {f[:-5] for f in os.listdir(SRC) if f.endswith('.lean') and f != 'Verify.lean'}
    if listed != actual:
        print(f"  MODULE DRIFT: missing from PARTS {sorted(actual - listed)}; "
              f"stale in PARTS {sorted(listed - actual)}")
        return False
    return True


def gen_verify():
    L = ["""/-
# Verification — every theorem, through `#print axioms`

Not part of the library: `SCD.lean` does not import it.  It imports `SCD` and
puts **every** theorem in the development through `#print axioms`, in the
reading order of the root file.

Generated by `tools/sync_report.py` from the sources, not curated, so nothing
can quietly fall out of the audit.  A clean run prints only `propext`,
`Classical.choice` and `Quot.sound`, and never `sorryAx`.
-/
import SCD

namespace SCD.Verify
"""]
    total = 0
    for title, _, mods in PARTS:
        L.append(f"\n/-! ## {title} -/\n")
        for mod in mods:
            ns = qualified(mod)
            if not ns:
                continue
            L.append(f"\n-- {mod}.lean")
            L += [f"#print axioms {n}" for n in ns]
            total += len(ns)
    L.append("\nend SCD.Verify")
    return '\n'.join(L) + '\n', total


def gen_index(total):
    def esc(n):
        return n.replace('_', r'\_\allowbreak ')
    out = [r"""\clearpage
\appendix
\section{定理索引：全部 %d 条}\label{sec:index}
\addcontentsline{toc}{section}{附录：定理索引}

本索引由 \texttt{tools/sync\_report.py} 从源码生成，非人工维护。
\textbf{每一条都在 \texttt{Verify.lean} 中经 \texttt{\#print axioms} 审计}，
故报告正文未展开叙述的定理\emph{并非未被检验}，只是未被叙述。

\footnotesize
\raggedright
""" % total]
    for _, zh, mods in PARTS:
        out.append("\n\\subsection*{%s}\n" % zh)
        for mod in mods:
            t = theorems(mod)
            if not t:
                continue
            names = ", ".join(r"\texttt{%s}" % esc(n) for n in t)
            out.append("\\noindent\\textbf{\\texttt{%s.lean}} (%d)\\quad %s\\par\\smallskip\n"
                       % (mod, len(t), names))
    out.append("\n\\normalsize\n")
    return ''.join(out)



# One-line Chinese description per module for the report's file table.
# Editorial content; the counts beside them are generated, these are not.
DESCRIPTIONS = {
    "Pattern": r"共用语汇：各向同性、平行、楔积、两个扇区计数与 A7",
    "Basic": r"A1 基底（环上，交换性不属于公理）、Kronecker 收缩原语",
    "Axioms": r"A2/A3/A5、红移、基准协变性",
    "Postulates": r"A1--A7 全在一处；证明基底只有一个载体",
    "Foundation": r"地基重建：标度即交换化，拆分被导出",
    "Signature": r"时间即漂移方向；号差由耗散导出",
    "Invariant": r"记账形式由迹导出",
    "Quantum": r"对易子即导数、Heisenberg 不确定性",
    "Direction": r"方向是定义表示（原说法已更正）",
    "Connection": r"曲率即对易子、Bianchi",
    "Coupling": r"两次缩放生成转动；耦合被词义强制",
    "Algebra": r"实秩一；筛出 Lorentz 族",
    "Dimension": r"方向是表示；比值不变；量值即单位",
    "Slice": r"广延即标签；转动是楔积；$k=3$ 唯一",
    "Axes": r"两难消解；轴数被迫为一",
    "Locus": r"A7；标签只活在各向异性轨迹上",
    "Dynamics": r"守恒出自 Bianchi",
    "Conformal": r"共形曲率恒等式、Ricci、标量曲率",
    "Frame": r"A4$'$ 方向性；旧公理禁止 Schwarzschild",
    "Unify": r"A4 是 A4$'$ 的各向同性轨迹",
    "Newton": r"线性化、Poisson、对偶数模型",
    "Diagonal": r"A4$'$ 对角度规的联络，经度规相容性认证；静态结构",
    "Schwarzschild": r"使倒数关系成立的相消",
    "RicciDiag": r"由联络导出 Ricci，引力链条闭合",
    "Vacuum": r"倒数关系的常数由渐近平直定出（已被指标形式取代）",
    "Reciprocity": r"倒数关系链条：全代数、无边界条件",
    "Determination": r"动力学重定义为决定关系：部分由补集决定，第三定律是影响的对称性",
    "Nonlinearity": r"$\beta$ 由真空方程导出：$2\beta=1+\gamma$，故 $\beta$ 非独立参数",
    "NCSize": r"各向异性非对易修正的量级：$\hbar$ 乘两个梯度的楔积；球对称静态下恒为零",
    "Response": r"扫描假设的确切内容：响应只经由阈值的个数；A5 与权重分次不足以逼出它",
    "Observer": r"观察者＝已越阈值集（登记为选择）：A4′+A6 使观察者非全序，但绝对性仍保留",
    "Observed": r"有观察者之后能得出与不能得出的：一致同意本身是观察者；漂移有结构性天花板；缺口是观察者触不到代数",
    "Internal": r"观察者成为系统的一部分：更大的观察者记录更少；扰动即力；但盲区未动",
    "Triple": r"观察者／被观察／过程三分：读序之差恰为对易子；A1 的第一个非交换模型",
    "Mutual": r"更正：被观察对的标度确在过程中但在读序之差里相消；三指标楔积作为对称候选",
    "Ordering": r"算子序：非交换提升不唯一且真空条件随之改变；静态构型不受影响",
    "Screen": r"观察者不变性筛：世界的预言不受影响，被记录的集合不是世界的函数",
    "Resolution": r"桥三：分辨作为理想滤链，不需要序；不相容性是 ad 在某分辨率下被读出",
    "Layers": r"不相容在有限分辨率出现；阈值由环算出而非公设；结果即不可分辨类，缺的是权重",
    "Spacing": r"取下与实测谱的那根线并证伪：单元素幂滤链给等间距，而实测间隔方差不为零",
    "Information": r"预言与输入在信息上不相交：任何预言都定不出自由数，只剩推导这一类路径",
    "Conversion": r"计数也定不出转换系数：Δρ 是永久输入；并记录我提了一条登记册已驳回的路线",
    "Overdetermination": r"输入出现两次才买得到预言；全部有量纲内容系于一个未做的识别",
    "RateWeight": r"耗散率是权零，故扫描换算不是规范耦合；第二条关系存在，剩下比例是否为一",
    "Bridge": r"沿漂移读代数：索引律推出扫描假设，比例恰为一；w/H₀ 链从三层输入降到两层",
    "Observations": r"两个识别获得类型；理论量相消，剩下两个测量必须给出同一个数",
    "Disconnect": r"宇宙学扇区与代数只共享名字不共享类型；撤回 Bridge 的一句断言",
    "Content": r"框架一直在写预层只是没有词汇；代数与阈值是同一个系统的两种描述",
    "Size": r"其余逃逸的分类：宇宙学那几个是内容的**大小**及其导数；与 G4 的权重是同一个缺口",
    "Valuation": r"模性 + record_union 给出观察者格上的容斥；结构接受权重，只是没有东西挑选它",
    "OneParameter": r"size 不是第二个自由度：斜率就是 ρ、原点是 A5 的；均匀密度正是让二者合一的那步",
    "Codimension2": r"余维错配的两条出路封死一条：线缺陷带 ℤ/2，其上无非零可加实源；三个拓扑整数全部出局",
    "DegreeSource": r"另一条出路也封死：群上可加且非负的源恒为零，所以引力的源不可能是拓扑电荷",
    "Anchor": r"概念是否锚定与预言的重新清点：八条中四条是定义上的恒等式",
    "Explanation": r"约束理论的解释力与预言力：预言＝解空间上的常量；约束非空亦非平凡",
    "Chain": r"引力链条重读：倒数关系已被导出；预言是 $\gamma=1$ 与因子 2",
    "Deflection": r"各向同性扇区恰好只给一半",
    "PPN": r"$\gamma=1$；付清另一半",
    "Precession": r"水星 $42.989''$",
    "Covariance": r"耗散下的局域协变性",
    "Singularity": r"无度规退化",
    "Waves": r"旋近动力学；守恒杀掉单极与偶极；总量桥接",
    "Flux": r"A6$\prime\prime$ 的连续极限：余维二处精确，缺口是同伦型不是分析",
    "Index": r"A6$'$ 换成指标形式：$\kappa$ 被定死，倒数关系不再需要渐近平直",
    "Horizon": r"无视界；波在光锥；熵是对数；无最小长度",
    "Witness": r"六个结构的见证：$\mathbb R[X]$ 承载精确标度平移",
    "ExpPoly": r"指数多项式：$e^p$ 是单位，故标度可变；A2 与 A4$'$ 第一次有了项",
    "Circle": r"圆环上的标度：梯度闭而不恰当；周期标度场不存在",
    "Gradient": r"度量 A2 假设了什么：几何只看梯度；A2 的内容是标度为单位，隐含的是梯度恰当",
    "Torus": r"n 维环面：非恰当梯度在任意维数都存在，不是一维的假象",
    "Amendment": r"A2 的修订：势对几何不可见且在基准平移下唯一；真正的内容是势的存在性",
    "Gauge": r"内禀对称性即标度花样稳定子",
    "Transport": r"输运由花样定出；规范自由即简并",
    "Axis": r"点粒子回来了",
    "Defect": r"标度缺陷、绕数即荷",
    "Charges": r"两个拓扑荷，恰一个被禁闭",
    "Particle": r"标签结构 $(\mathbb R,\mathbb Z/2,\mathbb Z)$",
    "Emergence": r"没有基本粒子",
    "Deformation": r"一阶形变、对应原理、CCR",
    "Crossed": r"精确非交换；$\hbar$ 是标度步长（见证见 Witness）",
    "Dual": r"A3$'$：标度群与其对偶；$\mathbb R$／$\mathbb T$ 两支；W2 单值性、W3 $\mathbb Z$-torsor",
    "NCConformal": r"非交换曲率；修正 $=[\sigma_i,\sigma_j]$，纯反对称",
    "Anisotropic": r"各向异性扇区：无经典挠率；修正即光速各向异性；$[\sigma_a,\sigma_b]$ 为领头项",
    "RG": r"标度流、Callan--Symanzik、EFT 塔",
    "Running": r"由计数导出线性跑动",
    "QCD": r"渐近自由、量纲嬗变",
    "Spectrum": r"阈值密度、$\mathrm{CV}$ 检验、换算",
    "Sources": r"三个被当成“源”的整数其实是三个不变量；自由数是形式强制的",
    "Weight": r"$\sigma\mapsto c\sigma$ 下的权重：只有引力跨越分次，故它携带单位",
    "Period": r"标度周期定不下来：格点路线被质谱排除，剩下的是换算",
    "Entropy": r"H 定理、不可逆性",
    "Light": r"类光锥标度无关",
    "Observation": r"红移属于观察者而非光",
    "Particles": r"标度比、寿命、阈值",
    "DarkMatter": r"探测失效",
    "DarkEnergy": r"耗散唯一性、de Sitter",
    "Positivity": r"公理不含能量条件：零能条件两侧皆可达",
    "Well": r"标度阱：喉道长度非零、无下界、Shapiro 两支",
    "Momentum": r"动量与质量壳：$E^2=m^2+p^2$ 由 A3+A4$'$ 导出",
    "Openness": r"A5 与 A6 是同一个子群的两句话",
    "Predictions": r"$w(q)$ 状态方程、数值核对",
    "Cosmos": r"$w$ 不演化；无初值；暗物质两路；共振宽度界",
    "Scanning": r"扫描式宇宙学：$w=-1$ 的隐藏前提；两个反常是一个数",
    "Attraction": r"源是计数故引力普适吸引；标度阱即空洞；计数界取代能量条件",
    "Native": r"框架自己的问题；两个时间箭头是一个序",
    "Data": r"与 DESI／PDG／Fermi-LAT 对质；第二个开关检验",
    "Color": r"块单值性（色解释已撤回）",
    "ColorAudit": r"块 $\ne$ 色块",
    "Codimension": r"（已被方向性 A4 取代）",
    "Expressive": r"可表达性（独立性结论已推翻）",
    "CrossCheck": r"跨扇区检验并不存在",
    "MassAudit": r"拓扑不决定质量律（撤回）",
    "Audit": r"登记册：撤回／更正／引用／假设",
}


def gen_filetable(total):
    """The report's per-file table: grouped by part, counts read from the sources."""
    missing = [m for _, _, ms in PARTS for m in ms if m not in DESCRIPTIONS]
    if missing:
        raise SystemExit(f"  DESCRIPTIONS missing entries for {missing}")
    rows = [r"\begin{center}", r"\begin{longtable}{lrl}", r"\toprule",
            r"文件 & 定理数 & 内容 \\", r"\midrule", r"\endhead"]
    for _, zh, mods in PARTS:
        rows.append(r"\multicolumn{3}{l}{\emph{%s}}\\" % zh)
        for mod in mods:
            rows.append(r"\texttt{%s.lean} & %d & %s \\"
                        % (mod, len(theorems(mod)), DESCRIPTIONS[mod]))
        rows.append(r"\midrule")
    nfiles = len([f for f in os.listdir(SRC) if f.endswith('.lean')])
    loc = sum(1 for f in os.listdir(SRC) if f.endswith('.lean') for _ in _read(f'{SRC}/{f}').splitlines())
    rows.append(r"\textbf{合计} & \textbf{%d} & %d 个文件，%d 行 Lean 代码 \\"
                % (total, nfiles, loc))
    rows += [r"\bottomrule", r"\end{longtable}", r"\end{center}"]
    return "\n".join(rows)

def check_citations():
    real = set()
    for f in os.listdir(SRC):
        if f.endswith('.lean'):
            real |= set(re.findall(DECL, _read(f'{SRC}/{f}'), re.M))
    tex = _read(TEX)
    bad = set()
    for m in re.findall(r'\\leanline\{([^}]*)\}', tex, re.S):
        for tok in re.split(r'[,\s]+', m.replace('\\_', '_')):
            t = tok.strip().rstrip('.').split('.')[-1]
            if t and '$' not in t and t not in real:
                bad.add(t)
    return sorted(bad)


def main():
    write = '--write' in sys.argv
    ok = check_modules()

    verify, total = gen_verify()
    vpath = os.path.join(SRC, 'Verify.lean')
    if _read(vpath) != verify:
        if write:
            _write(vpath, verify)
            print(f"  wrote Verify.lean ({total} theorems)")
        else:
            print(f"  DRIFT: Verify.lean is stale (sources have {total} theorems)")
            ok = False
    else:
        print(f"  Verify.lean in step ({total} theorems)")

    tex = _read(TEX)
    i = tex.find('\\clearpage\n\\appendix')
    j = tex.find('\\end{document}')
    if i > 0 and j > i:
        idx = gen_index(total)
        if tex[i:j].strip() != idx.strip():
            if write:
                _write(TEX, tex[:i] + idx + '\n' + tex[j:])
                print("  wrote the theorem index")
            else:
                print("  DRIFT: the theorem index is stale")
                ok = False
        else:
            print("  theorem index in step")

    tex = _read(TEX)
    lt = tex.find(r"\begin{longtable}{lrl}")
    if lt > 0:
        a = tex.rfind(r"\begin{center}", 0, lt)
        b = tex.find(r"\end{center}", tex.find(r"\end{longtable}", lt)) + len(r"\end{center}")
        tbl = gen_filetable(total)
        if tex[a:b].strip() != tbl.strip():
            if write:
                _write(TEX, tex[:a] + tbl + tex[b:])
                print("  wrote the file table")
            else:
                print("  DRIFT: the file table is stale")
                ok = False
        else:
            print("  file table in step")

    bad = check_citations()
    if bad:
        print(f"  BROKEN CITATIONS ({len(bad)}): {bad}")
        ok = False
    else:
        print("  every \\leanline citation resolves")

    tex = _read(TEX)
    quoted = set(re.findall(r'(\d{3,}) 条定理', tex))
    stale = {q for q in quoted if int(q) != total}
    if stale:
        print(f"  STALE COUNTS in the report: {sorted(stale)} (sources say {total})")
        ok = False
    else:
        print(f"  quoted counts match ({total})")

    print("OK" if ok else "DRIFT DETECTED")
    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
