#!/usr/bin/env python3
"""Keep Verify.lean, the report's file table, and the theorem index in step with
the sources — and fail loudly if anything has drifted.

Run from the repository root:

    python3 tools/sync_report.py            # check only, exits 1 on drift
    python3 tools/sync_report.py --write    # regenerate the generated blocks

What it enforces:
  * every theorem in SCD/*.lean appears in SCD/Verify.lean exactly once
  * every \\leanline{...} citation in the report names something that exists
  * the theorem counts quoted in the report match the sources
"""
import re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'SCD')
TEX = os.path.join(ROOT, 'paper', 'SCD.tex')

# reading order, mirroring SCD.lean; (part title in English, part title in Chinese, modules)
PARTS = [
    ("PART 0 — the postulates", "第一部分\\quad 公理",
     ["Basic", "Axioms", "Postulates"]),
    ("PART I — what the axioms force", "第二部分\\quad 公理逼出什么",
     ["Foundation", "Signature", "Invariant", "Quantum", "Direction", "Connection",
      "Coupling", "Algebra", "Dimension", "Slice", "Axes"]),
    ("PART II — the branch point", "第三部分\\quad 分叉点",
     ["Locus", "Dynamics"]),
    ("PART II.a — the isotropic sector", "第四部分\\quad 各向同性扇区",
     ["Conformal", "Frame", "Unify", "Newton", "Schwarzschild", "RicciDiag", "Vacuum",
      "Deflection", "PPN", "Precession", "Covariance", "Singularity", "Horizon", "Waves"]),
    ("PART II.c — witnesses", "第四部分附\\quad 结构的见证",
     ["Witness"]),
    ("PART II.b — the anisotropic sector", "第五部分\\quad 各向异性扇区",
     ["Gauge", "Transport", "Axis", "Defect", "Charges", "Particle", "Emergence"]),
    ("PART III — the quantum sector", "第六部分\\quad 量子扇区",
     ["Deformation", "Crossed", "NCConformal"]),
    ("PART IV — scale flow and content", "第七部分\\quad 标度流与内容",
     ["RG", "Running", "QCD", "Spectrum", "Entropy", "Light", "Observation",
      "Particles", "DarkMatter", "DarkEnergy"]),
    ("PART V — predictions and data", "第八部分\\quad 预言与数据",
     ["Predictions", "Cosmos", "Native", "Data"]),
    ("PART VI — the register", "第九部分\\quad 登记册",
     ["Color", "ColorAudit", "Codimension", "Expressive", "CrossCheck", "MassAudit", "Audit"]),
]

DECL = r'^(?:@\[[^\]]*\]\s*)?(?:theorem|def|noncomputable def|abbrev|structure|class|instance)\s+([A-Za-z_][\w₀-₉\']*)'
THM = r'^(?:@\[[^\]]*\]\s*)?theorem\s+([A-Za-z_][\w₀-₉\']*)'


def strip_docs(s):
    return re.sub(r'/-(?!!).*?-/', '', s, flags=re.S)


def theorems(mod):
    """Theorem names in a module, in source order."""
    return re.findall(THM, strip_docs(open(f'{SRC}/{mod}.lean').read()), re.M)


def qualified(mod):
    """Fully-qualified theorem names, tracking the namespace stack."""
    s = strip_docs(open(f'{SRC}/{mod}.lean').read())
    stack, out = [], []
    for line in s.split('\n'):
        m = re.match(r'\s*namespace\s+([A-Za-z_][\w.]*)', line)
        if m:
            stack.append(m.group(1)); continue
        m = re.match(r'\s*end\s+([A-Za-z_][\w.]*)\s*$', line)
        if m and stack and stack[-1].split('.')[-1] == m.group(1).split('.')[-1]:
            stack.pop(); continue
        m = re.match(r'\s*(?:@\[[^\]]*\]\s*)?theorem\s+([A-Za-z_][\w₀-₉\']*)', line)
        if m:
            out.append('.'.join(stack + [m.group(1)]))
    return out


def check_modules():
    listed = {m for _, _, ms in PARTS for m in ms}
    actual = {f[:-5] for f in os.listdir(SRC) if f.endswith('.lean') and f != 'Verify.lean'}
    if listed != actual:
        print(f"  MODULE DRIFT: missing from PARTS {sorted(actual - listed)}; "
              f"stale in PARTS {sorted(listed - actual)}")
        return False
    return True


def gen_verify():
    L = ["""/-
# Verification — every theorem, through `#print axioms`

Not part of the library: `SCD.lean` does not import it.  It imports `SCD` and
puts **every** theorem in the development through `#print axioms`, in the
reading order of the root file.

Generated by `tools/sync_report.py` from the sources, not curated, so nothing
can quietly fall out of the audit.  A clean run prints only `propext`,
`Classical.choice` and `Quot.sound`, and never `sorryAx`.
-/
import SCD

namespace SCD.Verify
"""]
    total = 0
    for title, _, mods in PARTS:
        L.append(f"\n/-! ## {title} -/\n")
        for mod in mods:
            ns = qualified(mod)
            if not ns:
                continue
            L.append(f"\n-- {mod}.lean")
            L += [f"#print axioms {n}" for n in ns]
            total += len(ns)
    L.append("\nend SCD.Verify")
    return '\n'.join(L) + '\n', total


def gen_index(total):
    def esc(n):
        return n.replace('_', r'\_\allowbreak ')
    out = [r"""\clearpage
\appendix
\section{定理索引：全部 %d 条}\label{sec:index}
\addcontentsline{toc}{section}{附录：定理索引}

本索引由 \texttt{tools/sync\_report.py} 从源码生成，非人工维护。
\textbf{每一条都在 \texttt{Verify.lean} 中经 \texttt{\#print axioms} 审计}，
故报告正文未展开叙述的定理\emph{并非未被检验}，只是未被叙述。

\footnotesize
\raggedright
""" % total]
    for _, zh, mods in PARTS:
        out.append("\n\\subsection*{%s}\n" % zh)
        for mod in mods:
            t = theorems(mod)
            if not t:
                continue
            names = ", ".join(r"\texttt{%s}" % esc(n) for n in t)
            out.append("\\noindent\\textbf{\\texttt{%s.lean}} (%d)\\quad %s\\par\\smallskip\n"
                       % (mod, len(t), names))
    out.append("\n\\normalsize\n")
    return ''.join(out)


def check_citations():
    real = set()
    for f in os.listdir(SRC):
        if f.endswith('.lean'):
            real |= set(re.findall(DECL, open(f'{SRC}/{f}').read(), re.M))
    tex = open(TEX).read()
    bad = set()
    for m in re.findall(r'\\leanline\{([^}]*)\}', tex, re.S):
        for tok in re.split(r'[,\s]+', m.replace('\\_', '_')):
            t = tok.strip().rstrip('.').split('.')[-1]
            if t and '$' not in t and t not in real:
                bad.add(t)
    return sorted(bad)


def main():
    write = '--write' in sys.argv
    ok = check_modules()

    verify, total = gen_verify()
    vpath = os.path.join(SRC, 'Verify.lean')
    if open(vpath).read() != verify:
        if write:
            open(vpath, 'w').write(verify)
            print(f"  wrote Verify.lean ({total} theorems)")
        else:
            print(f"  DRIFT: Verify.lean is stale (sources have {total} theorems)")
            ok = False
    else:
        print(f"  Verify.lean in step ({total} theorems)")

    tex = open(TEX).read()
    i = tex.find('\\clearpage\n\\appendix')
    j = tex.find('\\end{document}')
    if i > 0 and j > i:
        idx = gen_index(total)
        if tex[i:j].strip() != idx.strip():
            if write:
                open(TEX, 'w').write(tex[:i] + idx + '\n' + tex[j:])
                print("  wrote the theorem index")
            else:
                print("  DRIFT: the theorem index is stale")
                ok = False
        else:
            print("  theorem index in step")

    bad = check_citations()
    if bad:
        print(f"  BROKEN CITATIONS ({len(bad)}): {bad}")
        ok = False
    else:
        print("  every \\leanline citation resolves")

    tex = open(TEX).read()
    quoted = set(re.findall(r'(\d{3}) 条定理', tex))
    stale = {q for q in quoted if int(q) != total}
    if stale:
        print(f"  STALE COUNTS in the report: {sorted(stale)} (sources say {total})")
        ok = False
    else:
        print(f"  quoted counts match ({total})")

    print("OK" if ok else "DRIFT DETECTED")
    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
